
INSERT INTO `branches` VALUES (1, 'Ortigas Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (2, 'Marbel Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (3, 'Robinson\'s Ermita Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (4, 'Dewey Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (5, 'Davao Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (6, 'Gaisano Mall, Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (7, 'Tuguegarao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (8, 'Escolta,Sta. Cruz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (9, 'MH Del Pilar Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (10, 'Ermita', 2, NULL, NULL);
INSERT INTO `branches` VALUES (11, 'Agoo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (12, 'Baybay, Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (13, 'Miag-ao Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (14, 'Molave, Zamboanga Sur', 2, NULL, NULL);
INSERT INTO `branches` VALUES (15, 'Capistrano Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (16, 'Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (17, 'Las Piñas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (18, 'Quiapo Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (19, 'Sebogay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (20, 'Bantayan, Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (21, 'Cubao Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (22, 'Masbate Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (23, 'Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (24, 'Mandaue, Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (25, 'SM Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (26, 'U.N. Avenue - J. Bocobo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (27, '(SM Fairview)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (28, 'Caloocan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (29, 'Airport Road', 2, NULL, NULL);
INSERT INTO `branches` VALUES (30, 'Paseo de Roxas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (31, 'Plaridel, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (32, 'POEA', 2, NULL, NULL);
INSERT INTO `branches` VALUES (33, 'San Jose, Antique', 2, NULL, NULL);
INSERT INTO `branches` VALUES (34, 'Velez, Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (35, 'General Santos City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (36, 'SM City San Lazaro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (37, '5th Ave. (Caloocan)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (38, 'Aguinaldo Highway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (39, 'Alaminos, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (40, 'Almanza Uno, Las Piñas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (41, 'Amang Rodriguez Pasig', 2, NULL, NULL);
INSERT INTO `branches` VALUES (42, 'Antipolo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (43, 'Antique Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (44, 'Ayala', 2, NULL, NULL);
INSERT INTO `branches` VALUES (45, 'Ayala Alabang', 2, NULL, NULL);
INSERT INTO `branches` VALUES (46, 'Ayala Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (47, 'Araneta Cubao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (48, 'Bacolod - Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (49, 'Bacoor, Rotonda', 2, NULL, NULL);
INSERT INTO `branches` VALUES (50, 'Baguio City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (51, 'Bajada Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (52, 'Balagtas Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (53, 'Balanga, Bataan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (54, 'Baliwag, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (55, 'Bangkal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (56, 'Batangas City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (57, 'Bauan Batangas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (58, 'Bayan Malabon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (59, 'Benpres, Ortigas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (60, 'Better Living', 2, NULL, NULL);
INSERT INTO `branches` VALUES (61, 'Binakayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (62, 'Blumentritt', 2, NULL, NULL);
INSERT INTO `branches` VALUES (63, 'Bocobo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (64, 'Buendia Bel-Air', 2, NULL, NULL);
INSERT INTO `branches` VALUES (65, 'Butuan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (66, 'Cagayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (67, 'Cainta Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (68, 'Cainta Felix Bridge', 2, NULL, NULL);
INSERT INTO `branches` VALUES (69, 'Calapan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (70, 'Camarin Zabarte EBC', 2, NULL, NULL);
INSERT INTO `branches` VALUES (71, 'Camias, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (72, 'Carmen Rosales, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (73, 'Casimiro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (74, 'Cavite City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (75, 'CDO, Divisoria', 2, NULL, NULL);
INSERT INTO `branches` VALUES (76, 'Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (77, 'Centroplex Mall, Bacolod', 2, NULL, NULL);
INSERT INTO `branches` VALUES (78, 'Centropoles Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (79, 'Claveria, Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (80, 'CM Recto', 2, NULL, NULL);
INSERT INTO `branches` VALUES (81, 'Coastal Mall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (82, 'Commonwealth', 2, NULL, NULL);
INSERT INTO `branches` VALUES (83, 'Concepcion, Marikina', 2, NULL, NULL);
INSERT INTO `branches` VALUES (84, 'Corinthian', 2, NULL, NULL);
INSERT INTO `branches` VALUES (85, 'Cotabato City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (86, 'Crossing', 2, NULL, NULL);
INSERT INTO `branches` VALUES (87, 'Daet', 2, NULL, NULL);
INSERT INTO `branches` VALUES (88, 'Dagupan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (89, 'Dasmariñas Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (90, 'Davao - Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (91, 'Del Monte Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (92, 'Del Pilar', 2, NULL, NULL);
INSERT INTO `branches` VALUES (93, 'Dewey', 2, NULL, NULL);
INSERT INTO `branches` VALUES (94, 'Digos City Branch, Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (95, 'E. Aguinaldo Hiway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (96, 'E. Aguinaldo, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (97, 'E. Rodriguez St., Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (98, 'Elizabeth Mall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (99, 'Emilio Aguinaldo Hiway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (100, 'Escolta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (101, 'España', 2, NULL, NULL);
INSERT INTO `branches` VALUES (102, 'FEU, Morayta Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (103, 'Forbes Park', 2, NULL, NULL);
INSERT INTO `branches` VALUES (104, 'G. Mall Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (105, 'Gen Luna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (106, 'Gen Santos', 2, NULL, NULL);
INSERT INTO `branches` VALUES (107, 'Grace Park', 2, NULL, NULL);
INSERT INTO `branches` VALUES (108, 'Greenbelt Mall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (109, 'Greenhills, San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (110, 'Guiguinto, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (111, 'Harrison Plaza Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (112, 'Iligan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (113, 'Ilo-ilo Solis st. Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (114, 'Imus Plaza', 2, NULL, NULL);
INSERT INTO `branches` VALUES (115, 'Imus Nueno', 2, NULL, NULL);
INSERT INTO `branches` VALUES (116, 'Intramuros Passbook', 2, NULL, NULL);
INSERT INTO `branches` VALUES (117, 'Iznart St. Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (118, 'Jaro, Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (119, 'Kabihasnan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (120, 'Kalaw Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (121, 'Kalibo Aklan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (122, 'Koronadal City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (123, 'La Paz, Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (124, 'La Union', 2, NULL, NULL);
INSERT INTO `branches` VALUES (125, 'Lagro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (126, 'Laonglaan, Sampaloc', 2, NULL, NULL);
INSERT INTO `branches` VALUES (127, 'Lapasan, Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (128, 'Lapu-lapu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (129, 'Lemery', 2, NULL, NULL);
INSERT INTO `branches` VALUES (130, 'Libertad', 2, NULL, NULL);
INSERT INTO `branches` VALUES (131, 'Lipa Batangas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (132, 'Lucena', 2, NULL, NULL);
INSERT INTO `branches` VALUES (133, 'M.H. Del Pilar, U.N. Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (134, 'Mabini', 2, NULL, NULL);
INSERT INTO `branches` VALUES (135, 'Magallanes, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (136, 'Makati Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (137, 'Malabon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (138, 'Malay Balay Bukidnon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (139, 'Malinta Valenzuela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (140, 'Malolos, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (141, 'Mambaling, Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (142, 'Mangahan, Gen. Trias', 2, NULL, NULL);
INSERT INTO `branches` VALUES (143, 'Marbel', 2, NULL, NULL);
INSERT INTO `branches` VALUES (144, 'Marikina City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (145, 'Marvel, S. Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (146, 'Matina, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (147, 'Maypajo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (148, 'MEPZA II', 2, NULL, NULL);
INSERT INTO `branches` VALUES (149, 'Meycuayan Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (150, 'MIA Road', 2, NULL, NULL);
INSERT INTO `branches` VALUES (151, 'Midsayap, Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (152, 'Molino, Bacoor, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (153, 'Molo, Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (154, 'Montalban, Rizal Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (155, 'Morayta, Sampaloc', 2, NULL, NULL);
INSERT INTO `branches` VALUES (156, 'Muntinlupa City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (157, 'Naga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (158, 'NAIA', 2, NULL, NULL);
INSERT INTO `branches` VALUES (159, 'Novaliches Quirino Hi-way', 2, NULL, NULL);
INSERT INTO `branches` VALUES (160, 'Noveleta Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (161, 'Nueno, Imus, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (162, 'Nueva Viscaya', 2, NULL, NULL);
INSERT INTO `branches` VALUES (163, 'Olongapo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (164, 'Ormoc City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (165, 'Ororama, Cagayan de Oro City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (166, 'Ozamis City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (167, 'Paco', 2, NULL, NULL);
INSERT INTO `branches` VALUES (168, 'Pagadian City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (169, 'Palawan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (170, 'Pamplona', 2, NULL, NULL);
INSERT INTO `branches` VALUES (171, 'Paniqui, Tarlac', 2, NULL, NULL);
INSERT INTO `branches` VALUES (172, 'Parañaque', 2, NULL, NULL);
INSERT INTO `branches` VALUES (173, 'Paso De Blas, Valenzuela City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (174, 'Pateros Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (175, 'Pritil', 2, NULL, NULL);
INSERT INTO `branches` VALUES (176, 'Puerto Princesa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (177, 'Quezon Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (178, 'Quirante 2, Tagum City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (179, 'Quirino Highway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (180, 'Remedios, Taft', 2, NULL, NULL);
INSERT INTO `branches` VALUES (181, 'Retero Mayon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (182, 'Robinson Galleria, Ortigas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (183, 'Robinson Mall, Ermita', 2, NULL, NULL);
INSERT INTO `branches` VALUES (184, 'Rosales, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (185, 'Roxas City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (186, 'Roxas Capiz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (187, 'Rustans Cubao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (188, 'Sagay, Negros Occidental', 2, NULL, NULL);
INSERT INTO `branches` VALUES (189, 'Salcedo, Village', 2, NULL, NULL);
INSERT INTO `branches` VALUES (190, 'San Fernando City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (191, 'San Fernando La Union', 2, NULL, NULL);
INSERT INTO `branches` VALUES (192, 'San Fernando Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (193, 'San Jose, Nueva Ecija', 2, NULL, NULL);
INSERT INTO `branches` VALUES (194, 'San Mateo, Rizal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (195, 'San Pablo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (196, 'San Pedro, Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (197, 'Santa Rosa Balibago', 2, NULL, NULL);
INSERT INTO `branches` VALUES (198, 'Santiago, Isabela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (199, 'Session, Baguio', 2, NULL, NULL);
INSERT INTO `branches` VALUES (200, 'SF La Union', 2, NULL, NULL);
INSERT INTO `branches` VALUES (201, 'Shaw Boulevard', 2, NULL, NULL);
INSERT INTO `branches` VALUES (202, 'Silang, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (203, 'Silay City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (204, 'SM Bacoor', 2, NULL, NULL);
INSERT INTO `branches` VALUES (205, 'SM City Mandurriao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (206, 'SM Fairview', 2, NULL, NULL);
INSERT INTO `branches` VALUES (207, 'SM Southmall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (208, 'Solano, Nueva Vizcaya', 2, NULL, NULL);
INSERT INTO `branches` VALUES (209, 'Solis', 2, NULL, NULL);
INSERT INTO `branches` VALUES (210, 'Sorsogon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (211, 'Sta. Ana Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (212, 'Sta. Cruz Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (213, 'Sta Maria, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (214, 'Sta Monica', 2, NULL, NULL);
INSERT INTO `branches` VALUES (215, 'Sta. Ana', 2, NULL, NULL);
INSERT INTO `branches` VALUES (216, 'Sta. Lucia', 2, NULL, NULL);
INSERT INTO `branches` VALUES (217, 'Sta. Monica, Rizal, Nueva Ecija', 2, NULL, NULL);
INSERT INTO `branches` VALUES (218, 'Sucat Paranaque', 2, NULL, NULL);
INSERT INTO `branches` VALUES (219, 'T.M. Kalaw', 2, NULL, NULL);
INSERT INTO `branches` VALUES (220, 'Tabaco City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (221, 'Tabaco, Albay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (222, 'Tabuan, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (223, 'Tacloban City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (224, 'Taft', 2, NULL, NULL);
INSERT INTO `branches` VALUES (225, 'Tagaytay Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (226, 'Tagbilaran Bohol', 2, NULL, NULL);
INSERT INTO `branches` VALUES (227, 'Tagum City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (228, 'Tanauan Batangas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (229, 'Tanay Rizal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (230, 'Tarlac Hi-way', 2, NULL, NULL);
INSERT INTO `branches` VALUES (231, 'Tarlac City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (232, 'Taytay, Rizal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (233, 'Tayuman', 2, NULL, NULL);
INSERT INTO `branches` VALUES (234, 'Tutuban C.M. Recto', 2, NULL, NULL);
INSERT INTO `branches` VALUES (235, 'Victorias, Negros', 2, NULL, NULL);
INSERT INTO `branches` VALUES (236, 'Vigan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (237, 'Vigan Ilocos Sur', 2, NULL, NULL);
INSERT INTO `branches` VALUES (238, 'Virramall Greenhills (San Juan)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (239, 'Vito Cruz, Taft Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (240, 'West Triangle Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (241, 'Zamboanga City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (242, 'Zamora', 2, NULL, NULL);
INSERT INTO `branches` VALUES (243, 'Zapote, Las Piñas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (244, 'Rosario, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (245, 'Santolan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (246, 'Aklan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (247, 'Alabang', 2, NULL, NULL);
INSERT INTO `branches` VALUES (248, 'Almanza Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (249, 'Almanza Las Piñas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (250, 'Aurora Blvd. San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (251, 'Baclaran', 2, NULL, NULL);
INSERT INTO `branches` VALUES (252, 'Bacolod Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (253, 'Bacoor Cavite City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (254, 'Binondo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (255, 'Cauayan Isabela Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (256, 'Cebu MEPZ Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (257, 'Divisoria, Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (258, 'Dumaguete', 2, NULL, NULL);
INSERT INTO `branches` VALUES (259, 'EBC SNL San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (260, 'Adriatico', 2, NULL, NULL);
INSERT INTO `branches` VALUES (261, 'Cainta Poblacion', 2, NULL, NULL);
INSERT INTO `branches` VALUES (262, 'San Andres', 2, NULL, NULL);
INSERT INTO `branches` VALUES (263, 'Legarda', 2, NULL, NULL);
INSERT INTO `branches` VALUES (264, 'EDSA Monumento', 2, NULL, NULL);
INSERT INTO `branches` VALUES (265, 'Colon Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (266, 'Baliuag Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (267, 'Bustillos', 2, NULL, NULL);
INSERT INTO `branches` VALUES (268, 'Malibay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (269, 'Scout Albano, Quezon Ave.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (270, 'UV Colon Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (271, 'FTI Taguig', 2, NULL, NULL);
INSERT INTO `branches` VALUES (272, 'Gaisano, Roxas City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (273, 'Gen Luna, Ilo-ilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (274, 'GMA Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (275, 'GMA Carmona', 2, NULL, NULL);
INSERT INTO `branches` VALUES (276, 'GMA Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (277, 'Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (278, 'Juan Luna Paco', 2, NULL, NULL);
INSERT INTO `branches` VALUES (279, 'Los Baños', 2, NULL, NULL);
INSERT INTO `branches` VALUES (280, 'Malate', 2, NULL, NULL);
INSERT INTO `branches` VALUES (281, 'Mandaluyong Edsa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (282, 'Marbel South Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (283, 'Naga Caseres', 2, NULL, NULL);
INSERT INTO `branches` VALUES (284, 'New Alabang', 2, NULL, NULL);
INSERT INTO `branches` VALUES (285, 'P. Tuazon, Cubao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (286, 'Pasig Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (287, 'Pier South', 2, NULL, NULL);
INSERT INTO `branches` VALUES (288, 'Pioneer', 2, NULL, NULL);
INSERT INTO `branches` VALUES (289, 'Quezon Blvd. Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (290, 'Roosevelt Ave. SFDM, Q.C.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (291, 'Roosevelt, Muñoz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (292, 'SM City Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (293, 'Sucat Salvador', 2, NULL, NULL);
INSERT INTO `branches` VALUES (294, 'Tuguigarao Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (295, 'Tungko Branch, San Jose Delmonte City Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (296, 'Urdaneta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (297, 'Veterans Ave. Zamboanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (298, 'Alaminos Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (299, 'Angono, Rizal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (300, 'Araneta St. Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (301, 'Ayala Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (302, 'Bacalso St. Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (303, 'Balagtas, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (304, 'Banggoy Branch, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (305, 'Bangkal Branch, Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (306, 'Blumentritt, Ozamis', 2, NULL, NULL);
INSERT INTO `branches` VALUES (307, 'Butuan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (308, 'C3 Pajo, Caloocan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (309, 'Calamba Crossing', 2, NULL, NULL);
INSERT INTO `branches` VALUES (310, 'Calapan Branch Mindoro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (311, 'Candelaria Quezon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (312, 'Carriedo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (313, 'Cebu Mango Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (314, 'Central Market, Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (315, 'CM Recto Ave., Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (316, 'Dian, Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (317, 'Dipolog City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (318, 'Gen Luis, Novaliches', 2, NULL, NULL);
INSERT INTO `branches` VALUES (319, 'Fairview', 2, NULL, NULL);
INSERT INTO `branches` VALUES (320, 'Bahada Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (321, 'Edsa Central', 2, NULL, NULL);
INSERT INTO `branches` VALUES (322, 'Escario, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (323, 'Hemady, Aurora Blvd.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (324, 'Poblacion, Antipolo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (325, 'Sta. Mesa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (326, 'Valenzuela, Marulas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (327, 'Kalentong, Mandaluyong', 2, NULL, NULL);
INSERT INTO `branches` VALUES (328, 'Gapan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (329, 'Galo, Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (330, 'Gen. Santos South Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (331, 'Isetann Recto', 2, NULL, NULL);
INSERT INTO `branches` VALUES (332, 'Kamias EDSA', 2, NULL, NULL);
INSERT INTO `branches` VALUES (333, 'Kapasigan, Dasmariñas Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (334, 'Laoag Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (335, 'Lapasan Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (336, 'Lopez Jaena St. Ormoc City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (337, 'Magallanes, Makati Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (338, 'Market Market Taguig', 2, NULL, NULL);
INSERT INTO `branches` VALUES (339, 'Mary Mart Mall Branch - Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (340, 'Mckinley, Port Bonifacio', 2, NULL, NULL);
INSERT INTO `branches` VALUES (341, 'Montilla Blvd., Butuan City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (342, 'Muntinglupa Tunasan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (343, 'N. Domingo, San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (344, 'NAIA Kabihasnan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (345, 'Nasugbu, Batangas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (346, 'Pasong Tamo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (347, 'Rizal Ave. cor Garcia St., Dipolog City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (348, 'Robinson, Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (349, 'Robinsons, Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (350, 'Rufino Makati City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (351, 'Sarmiento Branch, Novaliches', 2, NULL, NULL);
INSERT INTO `branches` VALUES (352, 'SBMA Subic', 2, NULL, NULL);
INSERT INTO `branches` VALUES (353, 'SM Megamall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (354, 'Sta Rosa Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (355, 'Sultan Kudarat', 2, NULL, NULL);
INSERT INTO `branches` VALUES (356, 'Tabang Guiguinto, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (357, 'Tabunok Branch, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (358, 'Velez cor. Borja St. Cagayan de Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (359, 'West Ave. Q.C.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (360, 'SM Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (361, 'Maasin City Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (362, 'Congreso, Malolos', 2, NULL, NULL);
INSERT INTO `branches` VALUES (363, 'Valeria, Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (364, 'Bicutan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (365, 'Balayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (366, 'Anonas,Kamias', 2, NULL, NULL);
INSERT INTO `branches` VALUES (367, 'Cadiz City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (368, 'Times Plaza, UN Ave.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (369, 'Broadway Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (370, 'Port Area, South Harbour', 2, NULL, NULL);
INSERT INTO `branches` VALUES (371, 'Kabankalan, Negros Occidental', 2, NULL, NULL);
INSERT INTO `branches` VALUES (372, 'P. Faura', 2, NULL, NULL);
INSERT INTO `branches` VALUES (373, 'Guagua Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (374, 'Guimaras', 2, NULL, NULL);
INSERT INTO `branches` VALUES (375, 'Grace Park 11th Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (376, 'Aparri', 2, NULL, NULL);
INSERT INTO `branches` VALUES (377, 'Calamagui 2 Iligan Isabela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (378, 'Claveria', 2, NULL, NULL);
INSERT INTO `branches` VALUES (379, 'Marcos Highway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (380, 'Bogo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (381, 'V. Mapa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (382, 'Navotas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (383, 'Naga City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (384, 'Gen. Trias Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (385, 'Gumaca Quezon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (386, 'Candon Ilocos Sur', 2, NULL, NULL);
INSERT INTO `branches` VALUES (387, 'Valencia Bukidnon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (388, 'Tubod, Lanao Del Norte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (389, 'Maunlad, San Mateo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (390, 'Lebak, Sultan Kudarat', 2, NULL, NULL);
INSERT INTO `branches` VALUES (391, 'Catarman', 2, NULL, NULL);
INSERT INTO `branches` VALUES (392, 'YMCA Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (393, 'Talibon, Bohol', 2, NULL, NULL);
INSERT INTO `branches` VALUES (394, 'Tagbilaran City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (395, 'Siniloan, Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (396, 'Rosario, Batangas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (397, 'Gaisano City Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (398, 'Clark, Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (399, 'Camiguin', 2, NULL, NULL);
INSERT INTO `branches` VALUES (400, 'Aroceroz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (401, 'Malanday, Valenzuela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (402, 'Loyola Height Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (403, 'Timog', 2, NULL, NULL);
INSERT INTO `branches` VALUES (404, 'Jones Ave., Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (405, 'Anabu, Imus', 2, NULL, NULL);
INSERT INTO `branches` VALUES (406, 'Quirino, Bacnotan, La Union', 2, NULL, NULL);
INSERT INTO `branches` VALUES (407, 'Luneta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (408, 'Mambajao Camiguin', 2, NULL, NULL);
INSERT INTO `branches` VALUES (409, 'Odiongan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (410, 'Palompon Branch Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (411, 'Retiro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (412, 'San Pedro, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (413, 'Solano, N. E.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (414, 'Isabela (Negros Occidental)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (415, 'Bayan, Marikina', 2, NULL, NULL);
INSERT INTO `branches` VALUES (416, 'Gingoog City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (417, 'Mabuhay, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (418, 'Naval, Biliran', 2, NULL, NULL);
INSERT INTO `branches` VALUES (419, 'Sindangan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (420, 'Sorsogon, Sorsogon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (421, 'Tubigon, Bohol', 2, NULL, NULL);
INSERT INTO `branches` VALUES (422, 'Bayawan, Negros', 2, NULL, NULL);
INSERT INTO `branches` VALUES (423, 'Ever Gotesco', 2, NULL, NULL);
INSERT INTO `branches` VALUES (424, 'Masbate', 2, NULL, NULL);
INSERT INTO `branches` VALUES (425, 'NFA', 2, NULL, NULL);
INSERT INTO `branches` VALUES (426, 'Passi, Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (427, 'PGH', 2, NULL, NULL);
INSERT INTO `branches` VALUES (428, 'Rizal Park', 2, NULL, NULL);
INSERT INTO `branches` VALUES (429, 'Romblon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (430, 'Sta Cruz, Zambales', 2, NULL, NULL);
INSERT INTO `branches` VALUES (431, 'Tondo, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (432, 'Felix Ave., Cainta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (433, 'Isulan, Sultan Kudarat', 2, NULL, NULL);
INSERT INTO `branches` VALUES (434, 'JP Rizal, Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (435, 'Koronadal Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (436, 'Lacson, Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (437, 'Luzuriaga, Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (438, 'Batac', 2, NULL, NULL);
INSERT INTO `branches` VALUES (439, 'Danao,Cebu Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (440, 'Kidapawan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (441, 'Ali Mall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (442, 'Amelia Ave.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (443, 'Basilan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (444, 'Bepz, Mariveles', 2, NULL, NULL);
INSERT INTO `branches` VALUES (445, 'Catarman, Samar', 2, NULL, NULL);
INSERT INTO `branches` VALUES (446, 'COA', 2, NULL, NULL);
INSERT INTO `branches` VALUES (447, 'Bulan, Sorsogon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (448, 'Burgos, Tacloban City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (449, 'Carmona, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (450, 'Naic Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (451, 'Panabo, Davao del Norte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (452, 'Quirino Ave., Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (453, 'Banawe', 2, NULL, NULL);
INSERT INTO `branches` VALUES (454, 'North Edsa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (455, 'Pasay Rotonda', 2, NULL, NULL);
INSERT INTO `branches` VALUES (456, 'Rosario', 2, NULL, NULL);
INSERT INTO `branches` VALUES (457, 'Angeles City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (458, 'Gil Puyat', 2, NULL, NULL);
INSERT INTO `branches` VALUES (459, 'Domestic Road, Pasay City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (460, 'Bonifacio Global City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (461, 'Masbate City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (462, 'BPInoy', 2, NULL, NULL);
INSERT INTO `branches` VALUES (463, 'Mckinley, Fort Bonifacio', 2, NULL, NULL);
INSERT INTO `branches` VALUES (464, 'Sta. Cruz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (465, 'Faura', 2, NULL, NULL);
INSERT INTO `branches` VALUES (466, 'Pasay Libertad', 2, NULL, NULL);
INSERT INTO `branches` VALUES (467, 'Abad Santos', 2, NULL, NULL);
INSERT INTO `branches` VALUES (468, 'UN Avenue (Times Plaza)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (469, 'Libis Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (470, 'Malhacan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (471, 'University of Visayas Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (472, 'JM Basa,Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (473, 'Ninoy Aquino Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (474, 'Limay, Bataan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (475, 'Glorieta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (476, 'Padjak, Zamboanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (477, 'Imus, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (478, 'Santolan, Pasig', 2, NULL, NULL);
INSERT INTO `branches` VALUES (479, 'Kapasigan, Pasig City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (480, 'Robinsons, Novaliches', 2, NULL, NULL);
INSERT INTO `branches` VALUES (481, 'Calamba, Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (482, 'Tandag Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (483, 'Capitol Branch,Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (484, 'Novaliches-Lagro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (485, 'Basak, Lapu-lapu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (486, 'Matina Aplaya, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (487, 'Puerto Princesa, Palawan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (488, 'Ortigas, Mandaluyong', 2, NULL, NULL);
INSERT INTO `branches` VALUES (489, 'Norsagaray, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (490, 'Robinson Plaza', 2, NULL, NULL);
INSERT INTO `branches` VALUES (491, 'Oroquieta City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (492, 'UST, España', 2, NULL, NULL);
INSERT INTO `branches` VALUES (493, 'Highway,Tarlac City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (494, 'Bagong Barrio', 2, NULL, NULL);
INSERT INTO `branches` VALUES (495, 'P. Alonzo, Sta. Cruz, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (496, 'Sta. Rosa SM', 2, NULL, NULL);
INSERT INTO `branches` VALUES (497, 'Biñan Pavillion Mall', 2, NULL, NULL);
INSERT INTO `branches` VALUES (498, 'J.P. Laurel, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (499, 'UN, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (500, 'Intramuros, Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (501, 'Palawan, Puerto Princesa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (502, 'PNB Candon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (503, 'Mangaldan,Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (504, 'Capiz Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (505, 'Langkaan,Dasmarinas Cavite,Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (506, 'Ilagan Isabela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (507, 'U.N. Ave Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (508, 'Makati (main)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (509, 'Quezon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (510, 'Pedro Gil', 2, NULL, NULL);
INSERT INTO `branches` VALUES (511, 'Lucban, Quezon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (512, 'Virac, Catanduanes', 2, NULL, NULL);
INSERT INTO `branches` VALUES (513, 'Divisoria', 2, NULL, NULL);
INSERT INTO `branches` VALUES (514, 'Calbayog, Western Samar', 2, NULL, NULL);
INSERT INTO `branches` VALUES (515, 'Cebu - M.J. Cuenco', 2, NULL, NULL);
INSERT INTO `branches` VALUES (516, 'Toril,Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (517, 'Robinsons Palapala,Dasmarinas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (518, 'San Carlos, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (519, 'SM Clark, Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (520, 'Boni Ave.,Mandaluyong', 2, NULL, NULL);
INSERT INTO `branches` VALUES (521, 'Camiling, Tarlac', 2, NULL, NULL);
INSERT INTO `branches` VALUES (522, 'Balintawak Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (523, 'Climaco, Zamboanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (524, 'Gensan-Santiago', 2, NULL, NULL);
INSERT INTO `branches` VALUES (525, 'Lingayen, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (526, 'Dalandanan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (527, 'SM Dasmariñas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (528, 'Legaspi City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (529, 'Cash & Carry', 2, NULL, NULL);
INSERT INTO `branches` VALUES (530, 'to follow', 2, NULL, NULL);
INSERT INTO `branches` VALUES (531, 'Katipunan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (532, 'Balibago, Sta. Rosa, Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (533, 'Surigao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (534, 'Ligao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (535, 'Mc.Arthur Highway, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (536, 'Kamias , Anonas Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (537, 'Kalentong Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (538, 'Guadalupe Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (539, 'Yangon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (540, 'Gaisano City,Bacolod Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (541, 'Novaliches - Garmiento', 2, NULL, NULL);
INSERT INTO `branches` VALUES (542, 'St. Scholastica, Vito Cruz', 2, NULL, NULL);
INSERT INTO `branches` VALUES (543, 'Marilao, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (544, 'MEPZA I', 2, NULL, NULL);
INSERT INTO `branches` VALUES (545, 'Libertad,Mandaluyong', 2, NULL, NULL);
INSERT INTO `branches` VALUES (546, 'Surallah, South Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (547, 'SM Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (548, 'Iba, Zambales', 2, NULL, NULL);
INSERT INTO `branches` VALUES (549, 'C-5,Taguig Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (550, 'Manalili,Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (551, 'Bajada,Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (552, 'Sta. Maria, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (553, 'Alabel, Saranggani Province', 2, NULL, NULL);
INSERT INTO `branches` VALUES (554, 'NCC Matina Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (555, 'Times Plaza', 2, NULL, NULL);
INSERT INTO `branches` VALUES (556, 'Cabanatuan, Nueva Ecija', 2, NULL, NULL);
INSERT INTO `branches` VALUES (557, 'SM Marilao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (558, 'Tanza', 2, NULL, NULL);
INSERT INTO `branches` VALUES (559, 'Camp Aguinaldo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (560, 'Don Antonio, Commonwealth Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (561, 'Araneta Avenue, QC', 2, NULL, NULL);
INSERT INTO `branches` VALUES (562, 'Guiwan Branch Zamboanga City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (563, 'SM City, Sta. Mesa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (564, 'Riverbank, Marikina City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (565, 'Sta. Cruz,Zambales', 2, NULL, NULL);
INSERT INTO `branches` VALUES (566, 'Ortigas Center Pasig City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (567, 'Quirino Avenue Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (568, 'Accropolis, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (569, 'San Miguel', 2, NULL, NULL);
INSERT INTO `branches` VALUES (570, 'La Huerta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (571, 'Niugan, Cabuyao Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (572, 'Iloilo Main Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (573, 'SM Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (574, 'Delta, Quezon Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (575, 'San Miguel, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (576, 'Cabadbaran,Agusan Del Norte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (577, 'San Lazaro Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (578, 'EPZA Tramo, Rosario,Cavite Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (579, 'Ayala Center Glorietta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (580, 'Robinson Metro East EBC', 2, NULL, NULL);
INSERT INTO `branches` VALUES (581, 'Pacita San Pedro Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (582, 'Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (583, 'Cebu, Banilad Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (584, 'Rizal, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (585, 'Pandacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (586, 'Maasin City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (587, 'Binangonan, Rizal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (588, 'Rotonda Legazpi', 2, NULL, NULL);
INSERT INTO `branches` VALUES (589, 'BF Parañaque,Sucat', 2, NULL, NULL);
INSERT INTO `branches` VALUES (590, 'Bacolod Plaza Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (591, 'El Grande, BF Home Paranaque', 2, NULL, NULL);
INSERT INTO `branches` VALUES (592, 'EBC Ever Gotesco Recto', 2, NULL, NULL);
INSERT INTO `branches` VALUES (593, 'Guadalupe,Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (594, 'Novaliches - Bayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (595, 'San Carlos, Negros Occidental', 2, NULL, NULL);
INSERT INTO `branches` VALUES (596, 'Dalandanan, Valenzuela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (597, 'Cabuyao Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (598, 'Bocaue,Mc Arthur Highway', 2, NULL, NULL);
INSERT INTO `branches` VALUES (599, 'Panapaan,Molino Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (600, 'Ortigas,Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (601, 'Edsa,Greenhills', 2, NULL, NULL);
INSERT INTO `branches` VALUES (602, 'Leon Guinto', 2, NULL, NULL);
INSERT INTO `branches` VALUES (603, 'Santiago Blvd., Gen. Santos City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (604, 'Unimart Mall,Greenhills,San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (605, 'Ateneo, Roxas Ave, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (606, 'Dyanguren, Bangoy Davao', 2, NULL, NULL);
INSERT INTO `branches` VALUES (607, 'Sheerwood Place,L. Guinto Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (608, 'Arranque, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (609, 'East Ave. Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (610, 'Ortigas Extension, Cainta', 2, NULL, NULL);
INSERT INTO `branches` VALUES (611, 'Tungko Mangga,San Jose Del Monte,Bulacan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (612, 'IT Park,Lahog Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (613, 'San Francisco,Naga Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (614, 'Marulas', 2, NULL, NULL);
INSERT INTO `branches` VALUES (615, 'Cebu, Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (616, 'Dasmarinas Bayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (617, 'Diego Silang,Petron C-5', 2, NULL, NULL);
INSERT INTO `branches` VALUES (618, 'SM Valenzuela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (619, 'SM City Bacolod', 2, NULL, NULL);
INSERT INTO `branches` VALUES (620, 'Makati ,Medical Plaza', 2, NULL, NULL);
INSERT INTO `branches` VALUES (621, 'Pasay Road', 2, NULL, NULL);
INSERT INTO `branches` VALUES (622, 'SM City ,Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (623, 'C.M. Recto,Lipa City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (624, 'Uyangurin, R. Magsaysay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (625, 'Biñan,Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (626, 'NCCC Mall Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (627, 'Edsa Balintawak', 2, NULL, NULL);
INSERT INTO `branches` VALUES (628, 'Loyola, Katipunan Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (629, 'Edsa Bagong Barrio Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (630, 'A. Bonifacio Balintawak Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (631, 'Catbalogan City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (632, 'Mandurriao,Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (633, 'Edsa Shaw', 2, NULL, NULL);
INSERT INTO `branches` VALUES (634, 'Port Area, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (635, 'Calauag, Quezon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (636, 'F-Tañedo, Tarlac City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (637, 'Talisay City, Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (638, 'Muñoz Congressional Edsa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (639, 'Gen. Luna St., Iloilo City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (640, 'St. Francis Shaw', 2, NULL, NULL);
INSERT INTO `branches` VALUES (641, 'Makati City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (642, 'SM Rosario', 2, NULL, NULL);
INSERT INTO `branches` VALUES (643, 'Alabang,Muntinlupa City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (644, 'Poblacion,Muntinlupa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (645, 'Rosario,Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (646, 'San Pablo Laguna', 2, NULL, NULL);
INSERT INTO `branches` VALUES (647, 'Banilad, Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (648, 'Sandigang Bayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (649, 'Sogod, Southern Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (650, 'Osmena Blvd. cor Jasmen St., Cebu Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (651, 'Cebu Ayala,Business Park Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (652, 'SM,Cagayan De Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (653, 'Sta Ana,Manila Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (654, 'Pasig-Rotonda', 2, NULL, NULL);
INSERT INTO `branches` VALUES (655, 'Libertad,Bacolod City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (656, 'Isabela, Cagayan Valley', 2, NULL, NULL);
INSERT INTO `branches` VALUES (657, 'Walter Mart, Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (658, 'Macro,Buendia Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (659, 'Buendia', 2, NULL, NULL);
INSERT INTO `branches` VALUES (660, 'South Harbor, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (661, 'Capitol Branch,Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (662, 'Hinigaran, Negros Occidental', 2, NULL, NULL);
INSERT INTO `branches` VALUES (663, 'Zamora, Meycauayan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (664, 'Taguig Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (665, '982 Ortigas Emerald', 2, NULL, NULL);
INSERT INTO `branches` VALUES (666, 'Infanta,Quezon Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (667, 'Monumento', 2, NULL, NULL);
INSERT INTO `branches` VALUES (668, 'R. Salas Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (669, 'Fugoso St., Sta. Cruz, Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (670, 'Shopsville, Greenhills,San Juan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (671, 'Gingoog City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (672, 'SM Naga City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (673, 'Batangas Main', 2, NULL, NULL);
INSERT INTO `branches` VALUES (674, 'Gamboa.Legazpi St., Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (675, 'Albay Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (676, 'Bukidnon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (677, 'Muñoz, Roosevelt Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (678, 'Visayas Avenue, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (679, 'Talisay, Negros Occidental', 2, NULL, NULL);
INSERT INTO `branches` VALUES (680, 'Olo ng Apo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (681, 'Kapitolyo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (682, 'Victoria Tower Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (683, 'Capitol Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (684, 'Anabu, Imus, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (685, '7th Avenue,Caloocan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (686, 'Padre Faura -A Mabini', 2, NULL, NULL);
INSERT INTO `branches` VALUES (687, 'Evergotesco,Commonwealth', 2, NULL, NULL);
INSERT INTO `branches` VALUES (688, 'V. Luna,East Avenue.', 2, NULL, NULL);
INSERT INTO `branches` VALUES (689, 'Pioneer,General Santos City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (690, 'Malabon Central Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (691, 'J. Nakpil ,Taft Avenue Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (692, 'Alicia,Isabela Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (693, 'Greenhills', 2, NULL, NULL);
INSERT INTO `branches` VALUES (694, 'Justice Rumualdez Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (695, 'Robinson\'s Fairview', 2, NULL, NULL);
INSERT INTO `branches` VALUES (696, 'Congressional Ave. Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (697, 'Lanang,Davao Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (698, 'SM Lanang,Premier Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (699, 'Sta Cruz, Marinduque', 2, NULL, NULL);
INSERT INTO `branches` VALUES (700, 'EGI Tower Taft Ave. Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (701, 'Kawit Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (702, 'Salas Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (703, 'Sto Nino. , Roosevelt Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (704, 'Hyper Mart,Adriatico Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (705, 'Tutuban Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (706, 'Robinson\'s Express,Lipa Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (707, 'Panapaan,Bacoor Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (708, 'Madrigal Alabang Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (709, 'Marian ,Fairview Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (710, 'Bacoor,Zapote Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (711, 'Sta Rosa, Balibago', 2, NULL, NULL);
INSERT INTO `branches` VALUES (712, 'Sta Rosa Highway Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (713, 'Malate,Mabini Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (714, 'Cogon,CDO Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (715, 'Marasbaras,Tacloban City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (716, 'Ortigas,Greenhills Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (717, 'E.Lopez,Jaro,Iloilo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (718, 'Gapan, Nueva Ecija', 2, NULL, NULL);
INSERT INTO `branches` VALUES (719, 'Sto Nino,Cebu Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (720, 'Pretil', 2, NULL, NULL);
INSERT INTO `branches` VALUES (721, 'SM City BF Paranaque Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (722, 'BF Homes President Avenue Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (723, 'Mindanao Avenue Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (724, 'Caloocan,Camarin,Susano Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (725, 'Boracay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (726, 'FCIE,Dasmarinas Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (727, 'D. Macapagal Ave-Aseana Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (728, 'Bocaue, Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (729, 'Edsa, Magallanes', 2, NULL, NULL);
INSERT INTO `branches` VALUES (730, 'MEPZ 1', 2, NULL, NULL);
INSERT INTO `branches` VALUES (731, 'Pasong Tamo Ext.,Makati Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (732, 'BF Homes,Parañaque City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (733, 'Zambales Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (734, 'St. Lukes,Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (735, 'Atrium,Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (736, 'Mother Ignacia', 2, NULL, NULL);
INSERT INTO `branches` VALUES (737, 'Arellano,Dagupan City Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (738, 'Vertex One San LAzaro,Tayuman Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (739, 'Buendia cor Makati Ave. Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (740, 'Xavierville', 2, NULL, NULL);
INSERT INTO `branches` VALUES (741, 'La Trinidad,Benguet', 2, NULL, NULL);
INSERT INTO `branches` VALUES (742, 'Teacher\'s Village,Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (743, 'SM Lucena City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (744, 'Real St., Tacloban City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (745, 'Sabarte, Novaliches', 2, NULL, NULL);
INSERT INTO `branches` VALUES (746, 'Macapagal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (747, 'Yakal Chino Roces Avenue', 2, NULL, NULL);
INSERT INTO `branches` VALUES (748, 'Dagupan AB Fernandez Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (749, 'Dhalia Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (750, 'San Juan, Metro Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (751, 'Rizal,Malabon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (752, 'Balut,Tondo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (753, 'Chino Roces Extension', 2, NULL, NULL);
INSERT INTO `branches` VALUES (754, 'Tandang Sora Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (755, 'Larena, Siquijor', 2, NULL, NULL);
INSERT INTO `branches` VALUES (756, 'Poblacion, Siquijor', 2, NULL, NULL);
INSERT INTO `branches` VALUES (757, 'Novaliches - Sarmiento', 2, NULL, NULL);
INSERT INTO `branches` VALUES (758, 'Pasong Tamo La Fuerza Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (759, 'Sanchez Mira Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (760, 'Malvar', 2, NULL, NULL);
INSERT INTO `branches` VALUES (761, 'Shaw Sheridan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (762, 'Apalit, Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (763, 'Iloilo Solis Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (764, 'Munoz, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (765, 'Capas, Tarlac', 2, NULL, NULL);
INSERT INTO `branches` VALUES (766, 'Deparo Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (767, 'Gorordo,Cebu Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (768, 'Pala-Pala Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (769, 'Roxas, Esabela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (770, 'Manila', 2, NULL, NULL);
INSERT INTO `branches` VALUES (771, 'Reposo, Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (772, 'Taft, Pasay', 2, NULL, NULL);
INSERT INTO `branches` VALUES (773, 'Centrio Ayala, Cagayan De Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (774, 'Penafrancia, Naga City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (775, 'Bulacan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (776, 'Palo, Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (777, 'Carigara, Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (778, 'Robinson\'s Place Tacloban', 2, NULL, NULL);
INSERT INTO `branches` VALUES (779, 'Bais City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (780, 'Quirino, Davao City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (781, 'San Mateo, Isabela', 2, NULL, NULL);
INSERT INTO `branches` VALUES (782, 'Cabacan, North Cotabato', 2, NULL, NULL);
INSERT INTO `branches` VALUES (783, 'Terraces Fairview', 2, NULL, NULL);
INSERT INTO `branches` VALUES (784, 'Mabalacat, Pampanga', 2, NULL, NULL);
INSERT INTO `branches` VALUES (785, 'Waltermart-Bicutan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (786, 'Tabo-an, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (787, 'ONE E-COMCENTER (MOA)', 2, NULL, NULL);
INSERT INTO `branches` VALUES (788, 'Robinson\'s Galleria Cebu', 2, NULL, NULL);
INSERT INTO `branches` VALUES (789, 'Mabolo, Cebu City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (790, 'Bacolod - Hilado', 2, NULL, NULL);
INSERT INTO `branches` VALUES (791, 'Kamuning, Quezon City', 2, NULL, NULL);
INSERT INTO `branches` VALUES (792, 'Bayambang, Pangasinan', 2, NULL, NULL);
INSERT INTO `branches` VALUES (793, 'Hinunangan, Southern Leyte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (794, 'Masinag', 2, NULL, NULL);
INSERT INTO `branches` VALUES (795, 'San Nicolas, Ilocos Norte', 2, NULL, NULL);
INSERT INTO `branches` VALUES (796, 'Calapan City, Oriental Mindoro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (797, 'Puregold, Noveleta, Cavite', 2, NULL, NULL);
INSERT INTO `branches` VALUES (798, 'tarla', 2, NULL, NULL);
INSERT INTO `branches` VALUES (799, 'SM North Edsa', 2, NULL, NULL);
INSERT INTO `branches` VALUES (800, 'Tagudin, Ilocos Sur', 2, NULL, NULL);
INSERT INTO `branches` VALUES (801, 'Villamor Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (802, 'Roxas, Oriental Mindoro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (803, 'Pablo Ocampo Extension', 2, NULL, NULL);
INSERT INTO `branches` VALUES (804, 'Consalacio,Cebu Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (805, 'Mintal', 2, NULL, NULL);
INSERT INTO `branches` VALUES (806, 'Pavia,Iloilo', 2, NULL, NULL);
INSERT INTO `branches` VALUES (807, 'Limketkai, Cagayan De Oro', 2, NULL, NULL);
INSERT INTO `branches` VALUES (808, 'Fishermall-Malabon', 2, NULL, NULL);
INSERT INTO `branches` VALUES (809, 'Padada, Davao del Sur', 2, NULL, NULL);
INSERT INTO `branches` VALUES (810, 'N. Garcia - Makati', 2, NULL, NULL);
INSERT INTO `branches` VALUES (811, 'Novaliches-Trees Residence', 2, NULL, NULL);
INSERT INTO `branches` VALUES (812, 'Roxas Oriental, Mindoro Branch', 2, NULL, NULL);
INSERT INTO `branches` VALUES (813, 'Ipil Branch', 2, NULL, NULL);
