
INSERT INTO `clinics` VALUES (1, 'Arguelles', '1271 Zobel Roxas Malate 1004 Manila', '5215353', 'Dr Joey Arguelles', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (2, 'Physicians', '533 UN Avenue cor San Carlos St, 4/F Physicians Tower Ermita Mnl', '5240626', 'Odette', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (3, 'Medical Centre for Seamen', 'The Netherlands', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (4, 'Absence Control Manila', 'UN Avenue Manila', NULL, 'Dr Salvador', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (5, 'Virginia P. Tupas-Taleon, M.D.', 'Ground Floor YMCA Bldg. IZNART St., Iloilo City', '(033) 3372071', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (6, 'Manila Doctors Hospital', 'U.N. Avenue, Ermita, Manila', '524-3011', 'Dr. Roehl Salvador', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (7, 'Medical Dental Tests Center, Inc.', '3rd Floor, Dallcon II Bldg., 164 Aurora Blvd. San Juan City', '(02) 7442638 / (02) 7442641', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (8, 'St. Thomas Diagnostic, Medical and Dental Clinic, Inc.', '2nd Flr. PWU International House Bldg. 1724 Leon Guinto ', '(02) 5367664', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (9, 'RBG Medical and Dental Clinic', '1353 A. Mabini St., Ermita, Manila (Resoro Building)', '5211039', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (10, 'Paragu Medical Centre', 'No. 140/144, Anawrahta Road, Botahtaung Township, Yangon Myanmar', '951-294616', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (11, 'Bureau of Quarantine Manila', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (12, 'Paragu Medical Centre ', 'No. 140/144 Anawrahta Road,Botahtaung Township,Yangon,Myanmar', '951-294616', 'Dr. Thida Aung', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (13, 'Maritime Medical and Laboratory Clinic, Inc.', '2/F Paragon Tower, 531 A. Flores St., Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (14, 'Terveystalo', 'Soumen,Terveystalo OY,Aninkaistenkatu 13,20100,Turku,Finland', NULL, 'Seija Hendriksson', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (15, 'Clinicomed Inc.', '3/F Ma. Daniel Bldg.,470 San Andres cor M.H. Del Pilar Sts.,Makate Manila', '632 521 5499', 'Leticia C. Abesamis M.D.', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (16, 'Dr. David Chalmers MA FRCS D Occ Med', 'Snaefell Surgery,Cushag Road,Anaghcoar,Douglas,Isle of man IM2 2BZ', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (17, 'Angelus Medical Clinic, Inc.', '104 V.A Rufino Street, Legaspi Village Makati City', '815-1938', NULL, '\n', 2, NULL, NULL);
INSERT INTO `clinics` VALUES (18, 'Galenus Clinic Inc.', '3/F Ferguson Tower, M.H. Del Pilar St. cor A. Flores St., Ermita, Manila', NULL, 'Wenceslao S. Llauderes, MD', 'Medical Director', 2, NULL, NULL);
INSERT INTO `clinics` VALUES (19, 'Transnational Medical and Diagnostic Center', '551 Cabildo St., Camarinero II Bldg. Intramuros, Manila', '525-1674', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (20, 'Supercare Medical Services, Inc.', '315 VELCO Center R.S. Oca Cor., A.C. Delgado St., Port Area Manila', '310-8855; 521-9699', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (21, 'Supercare Medical Serives,Inc.', '315 VELCO Center R.S. Oca Cor., A.C. Delgado St.,Port Area,Manila', '310-8855', 'Pascualito D. Gutay MD', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (22, 'Ygeia Medical Center,Inc.', '2081 President Quirino Ave., Pandacan,Manila', '632 562 7465', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (23, 'Ippokratis Diagnostic Services Center Inc.', 'Second Floor Victoria Bldg.,429 United Nation Ave.,Ermita,Manila', '524-6561 ; 524-6639', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (24, 'Halcyon Marine Health CAre System,Inc.', '10/F,unit A & B,Trafalgar Plaza,105 HV del Costa St.,Salcedo Village,Makati City', '864-0213 to 14', 'Glennda P. Estores-Canlas,MD', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (25, 'Dr Patrick Ireland', '1913,Route De Cannes,06560,Valbonne-France', '+33 4 93 12 95 66', 'Dr Patrick Ireland', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (26, 'American Outpatient Clinic (American Hospital,Inc.)', '2nd Flr FEMII Building.,A.Soriano Jr. Ave.,Intramuros,Manila', '+63 527-1611', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (27, 'Helplabs Medical and Diagnostic Center,Inc.', '3rd Flr., San Luis Bldg.,Ma Orosa cor. T.M. Kalaw,Ermita,Manila', '(092) 254-77-44', 'Leigh Di Avril P. Agdeppa', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (28, 'Our Lady of Fatima Clinic', '942 P. Campa St.,Sampaloc,Manila,Philippines', '733-3528', 'Roel B. Pidlaoan M.D.', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (29, 'OCW Medical Clinic,Inc.', '3F Regent Bldg., 1415 Gen. Luna St.,Ermita,Manila', '536-4866', 'Marcel Joseph I. Alcaraz,MD', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (30, 'Health Metrics, Inc.', '1157 Don Chino Roces Ave., San Antonio Village, 1203 Makati City', '7951234', NULL, NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (31, 'S.M. Lazo Medical Clinic, Inc.', '1755 Taft Avenue cor. J.Nakpil Street, Malate Manila', '5241891', 'Joseph Julius P. Cuebillas M.D.', NULL, 2, NULL, NULL);
INSERT INTO `clinics` VALUES (32, 'Eastern Doctors Clinic', 'Suite G-1 Bel-Air Apts. 1020 Roxas Blvd., Ermita, Manila', '(02) 528-4716 / 5212708 loc. 3010', NULL, NULL, 2, NULL, NULL);
