/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80020
 Source Host           : localhost:3306
 Source Schema         : seabasedb

 Target Server Type    : MySQL
 Target Server Version : 80020
 File Encoding         : 65001

 Date: 21/02/2021 18:22:06
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for countries
-- ----------------------------

-- ----------------------------
-- Records of countries
-- ----------------------------
BEGIN;
INSERT INTO `countries` VALUES (1, 'AF', 'Afghanistan', NULL, NULL);
INSERT INTO `countries` VALUES (2, 'AX', 'Åland Islands', NULL, NULL);
INSERT INTO `countries` VALUES (3, 'AL', 'Albania', NULL, NULL);
INSERT INTO `countries` VALUES (4, 'DZ', 'Algeria', NULL, NULL);
INSERT INTO `countries` VALUES (5, 'AS', 'American Samoa', NULL, NULL);
INSERT INTO `countries` VALUES (6, 'AD', 'AndorrA', NULL, NULL);
INSERT INTO `countries` VALUES (7, 'AO', 'Angola', NULL, NULL);
INSERT INTO `countries` VALUES (8, 'AI', 'Anguilla', NULL, NULL);
INSERT INTO `countries` VALUES (9, 'AQ', 'Antarctica', NULL, NULL);
INSERT INTO `countries` VALUES (10, 'AG', 'Antigua and Barbuda', NULL, NULL);
INSERT INTO `countries` VALUES (11, 'AR', 'Argentina', NULL, NULL);
INSERT INTO `countries` VALUES (12, 'AM', 'Armenia', NULL, NULL);
INSERT INTO `countries` VALUES (13, 'AW', 'Aruba', NULL, NULL);
INSERT INTO `countries` VALUES (14, 'AU', 'Australia', NULL, NULL);
INSERT INTO `countries` VALUES (15, 'AT', 'Austria', NULL, NULL);
INSERT INTO `countries` VALUES (16, 'AZ', 'Azerbaijan', NULL, NULL);
INSERT INTO `countries` VALUES (17, 'BS', 'Bahamas', NULL, NULL);
INSERT INTO `countries` VALUES (18, 'BH', 'Bahrain', NULL, NULL);
INSERT INTO `countries` VALUES (19, 'BD', 'Bangladesh', NULL, NULL);
INSERT INTO `countries` VALUES (20, 'BB', 'Barbados', NULL, NULL);
INSERT INTO `countries` VALUES (21, 'BY', 'Belarus', NULL, NULL);
INSERT INTO `countries` VALUES (22, 'BE', 'Belgium', NULL, NULL);
INSERT INTO `countries` VALUES (23, 'BZ', 'Belize', NULL, NULL);
INSERT INTO `countries` VALUES (24, 'BJ', 'Benin', NULL, NULL);
INSERT INTO `countries` VALUES (25, 'BM', 'Bermuda', NULL, NULL);
INSERT INTO `countries` VALUES (26, 'BT', 'Bhutan', NULL, NULL);
INSERT INTO `countries` VALUES (27, 'BO', 'Bolivia', NULL, NULL);
INSERT INTO `countries` VALUES (28, 'BA', 'Bosnia and Herzegovina', NULL, NULL);
INSERT INTO `countries` VALUES (29, 'BW', 'Botswana', NULL, NULL);
INSERT INTO `countries` VALUES (30, 'BV', 'Bouvet Island', NULL, NULL);
INSERT INTO `countries` VALUES (31, 'BR', 'Brazil', NULL, NULL);
INSERT INTO `countries` VALUES (32, 'IO', 'British Indian Ocean Territory', NULL, NULL);
INSERT INTO `countries` VALUES (33, 'BN', 'Brunei Darussalam', NULL, NULL);
INSERT INTO `countries` VALUES (34, 'BG', 'Bulgaria', NULL, NULL);
INSERT INTO `countries` VALUES (35, 'BF', 'Burkina Faso', NULL, NULL);
INSERT INTO `countries` VALUES (36, 'BI', 'Burundi', NULL, NULL);
INSERT INTO `countries` VALUES (37, 'KH', 'Cambodia', NULL, NULL);
INSERT INTO `countries` VALUES (38, 'CM', 'Cameroon', NULL, NULL);
INSERT INTO `countries` VALUES (39, 'CA', 'Canada', NULL, NULL);
INSERT INTO `countries` VALUES (40, 'CV', 'Cape Verde', NULL, NULL);
INSERT INTO `countries` VALUES (41, 'KY', 'Cayman Islands', NULL, NULL);
INSERT INTO `countries` VALUES (42, 'CF', 'Central African Republic', NULL, NULL);
INSERT INTO `countries` VALUES (43, 'TD', 'Chad', NULL, NULL);
INSERT INTO `countries` VALUES (44, 'CL', 'Chile', NULL, NULL);
INSERT INTO `countries` VALUES (45, 'CN', 'China', NULL, NULL);
INSERT INTO `countries` VALUES (46, 'CX', 'Christmas Island', NULL, NULL);
INSERT INTO `countries` VALUES (47, 'CC', 'Cocos (Keeling) Islands', NULL, NULL);
INSERT INTO `countries` VALUES (48, 'CO', 'Colombia', NULL, NULL);
INSERT INTO `countries` VALUES (49, 'KM', 'Comoros', NULL, NULL);
INSERT INTO `countries` VALUES (50, 'CG', 'Congo', NULL, NULL);
INSERT INTO `countries` VALUES (51, 'CD', 'Congo, The Democratic Republic of the', NULL, NULL);
INSERT INTO `countries` VALUES (52, 'CK', 'Cook Islands', NULL, NULL);
INSERT INTO `countries` VALUES (53, 'CR', 'Costa Rica', NULL, NULL);
INSERT INTO `countries` VALUES (54, 'CI', 'Cote D\'Ivoire', NULL, NULL);
INSERT INTO `countries` VALUES (55, 'HR', 'Croatia', NULL, NULL);
INSERT INTO `countries` VALUES (56, 'CU', 'Cuba', NULL, NULL);
INSERT INTO `countries` VALUES (57, 'CY', 'Cyprus', NULL, NULL);
INSERT INTO `countries` VALUES (58, 'CZ', 'Czech Republic', NULL, NULL);
INSERT INTO `countries` VALUES (59, 'DK', 'Denmark', NULL, NULL);
INSERT INTO `countries` VALUES (60, 'DJ', 'Djibouti', NULL, NULL);
INSERT INTO `countries` VALUES (61, 'DM', 'Dominica', NULL, NULL);
INSERT INTO `countries` VALUES (62, 'DO', 'Dominican Republic', NULL, NULL);
INSERT INTO `countries` VALUES (63, 'EC', 'Ecuador', NULL, NULL);
INSERT INTO `countries` VALUES (64, 'EG', 'Egypt', NULL, NULL);
INSERT INTO `countries` VALUES (65, 'SV', 'El Salvador', NULL, NULL);
INSERT INTO `countries` VALUES (66, 'GQ', 'Equatorial Guinea', NULL, NULL);
INSERT INTO `countries` VALUES (67, 'ER', 'Eritrea', NULL, NULL);
INSERT INTO `countries` VALUES (68, 'EE', 'Estonia', NULL, NULL);
INSERT INTO `countries` VALUES (69, 'ET', 'Ethiopia', NULL, NULL);
INSERT INTO `countries` VALUES (70, 'FK', 'Falkland Islands (Malvinas)', NULL, NULL);
INSERT INTO `countries` VALUES (71, 'FO', 'Faroe Islands', NULL, NULL);
INSERT INTO `countries` VALUES (72, 'FJ', 'Fiji', NULL, NULL);
INSERT INTO `countries` VALUES (73, 'FI', 'Finland', NULL, NULL);
INSERT INTO `countries` VALUES (74, 'FR', 'France', NULL, NULL);
INSERT INTO `countries` VALUES (75, 'GF', 'French Guiana', NULL, NULL);
INSERT INTO `countries` VALUES (76, 'PF', 'French Polynesia', NULL, NULL);
INSERT INTO `countries` VALUES (77, 'TF', 'French Southern Territories', NULL, NULL);
INSERT INTO `countries` VALUES (78, 'GA', 'Gabon', NULL, NULL);
INSERT INTO `countries` VALUES (79, 'GM', 'Gambia', NULL, NULL);
INSERT INTO `countries` VALUES (80, 'GE', 'Georgia', NULL, NULL);
INSERT INTO `countries` VALUES (81, 'DE', 'Germany', NULL, NULL);
INSERT INTO `countries` VALUES (82, 'GH', 'Ghana', NULL, NULL);
INSERT INTO `countries` VALUES (83, 'GI', 'Gibraltar', NULL, NULL);
INSERT INTO `countries` VALUES (84, 'GR', 'Greece', NULL, NULL);
INSERT INTO `countries` VALUES (85, 'GL', 'Greenland', NULL, NULL);
INSERT INTO `countries` VALUES (86, 'GD', 'Grenada', NULL, NULL);
INSERT INTO `countries` VALUES (87, 'GP', 'Guadeloupe', NULL, NULL);
INSERT INTO `countries` VALUES (88, 'GU', 'Guam', NULL, NULL);
INSERT INTO `countries` VALUES (89, 'GT', 'Guatemala', NULL, NULL);
INSERT INTO `countries` VALUES (90, 'GG', 'Guernsey', NULL, NULL);
INSERT INTO `countries` VALUES (91, 'GN', 'Guinea', NULL, NULL);
INSERT INTO `countries` VALUES (92, 'GW', 'Guinea-Bissau', NULL, NULL);
INSERT INTO `countries` VALUES (93, 'GY', 'Guyana', NULL, NULL);
INSERT INTO `countries` VALUES (94, 'HT', 'Haiti', NULL, NULL);
INSERT INTO `countries` VALUES (95, 'HM', 'Heard Island and Mcdonald Islands', NULL, NULL);
INSERT INTO `countries` VALUES (96, 'VA', 'Holy See (Vatican City State)', NULL, NULL);
INSERT INTO `countries` VALUES (97, 'HN', 'Honduras', NULL, NULL);
INSERT INTO `countries` VALUES (98, 'HK', 'Hong Kong', NULL, NULL);
INSERT INTO `countries` VALUES (99, 'HU', 'Hungary', NULL, NULL);
INSERT INTO `countries` VALUES (100, 'IS', 'Iceland', NULL, NULL);
INSERT INTO `countries` VALUES (101, 'IN', 'India', NULL, NULL);
INSERT INTO `countries` VALUES (102, 'ID', 'Indonesia', NULL, NULL);
INSERT INTO `countries` VALUES (103, 'IR', 'Iran, Islamic Republic Of', NULL, NULL);
INSERT INTO `countries` VALUES (104, 'IQ', 'Iraq', NULL, NULL);
INSERT INTO `countries` VALUES (105, 'IE', 'Ireland', NULL, NULL);
INSERT INTO `countries` VALUES (106, 'IM', 'Isle of Man', NULL, NULL);
INSERT INTO `countries` VALUES (107, 'IL', 'Israel', NULL, NULL);
INSERT INTO `countries` VALUES (108, 'IT', 'Italy', NULL, NULL);
INSERT INTO `countries` VALUES (109, 'JM', 'Jamaica', NULL, NULL);
INSERT INTO `countries` VALUES (110, 'JP', 'Japan', NULL, NULL);
INSERT INTO `countries` VALUES (111, 'JE', 'Jersey', NULL, NULL);
INSERT INTO `countries` VALUES (112, 'JO', 'Jordan', NULL, NULL);
INSERT INTO `countries` VALUES (113, 'KZ', 'Kazakhstan', NULL, NULL);
INSERT INTO `countries` VALUES (114, 'KE', 'Kenya', NULL, NULL);
INSERT INTO `countries` VALUES (115, 'KI', 'Kiribati', NULL, NULL);
INSERT INTO `countries` VALUES (116, 'KP', 'Korea, Democratic People\'S Republic of', NULL, NULL);
INSERT INTO `countries` VALUES (117, 'KR', 'Korea, Republic of', NULL, NULL);
INSERT INTO `countries` VALUES (118, 'KW', 'Kuwait', NULL, NULL);
INSERT INTO `countries` VALUES (119, 'KG', 'Kyrgyzstan', NULL, NULL);
INSERT INTO `countries` VALUES (120, 'LA', 'Lao People\'S Democratic Republic', NULL, NULL);
INSERT INTO `countries` VALUES (121, 'LV', 'Latvia', NULL, NULL);
INSERT INTO `countries` VALUES (122, 'LB', 'Lebanon', NULL, NULL);
INSERT INTO `countries` VALUES (123, 'LS', 'Lesotho', NULL, NULL);
INSERT INTO `countries` VALUES (124, 'LR', 'Liberia', NULL, NULL);
INSERT INTO `countries` VALUES (125, 'LY', 'Libyan Arab Jamahiriya', NULL, NULL);
INSERT INTO `countries` VALUES (126, 'LI', 'Liechtenstein', NULL, NULL);
INSERT INTO `countries` VALUES (127, 'LT', 'Lithuania', NULL, NULL);
INSERT INTO `countries` VALUES (128, 'LU', 'Luxembourg', NULL, NULL);
INSERT INTO `countries` VALUES (129, 'MO', 'Macao', NULL, NULL);
INSERT INTO `countries` VALUES (130, 'MK', 'Macedonia, The Former Yugoslav Republic of', NULL, NULL);
INSERT INTO `countries` VALUES (131, 'MG', 'Madagascar', NULL, NULL);
INSERT INTO `countries` VALUES (132, 'MW', 'Malawi', NULL, NULL);
INSERT INTO `countries` VALUES (133, 'MY', 'Malaysia', NULL, NULL);
INSERT INTO `countries` VALUES (134, 'MV', 'Maldives', NULL, NULL);
INSERT INTO `countries` VALUES (135, 'ML', 'Mali', NULL, NULL);
INSERT INTO `countries` VALUES (136, 'MT', 'Malta', NULL, NULL);
INSERT INTO `countries` VALUES (137, 'MH', 'Marshall Islands', NULL, NULL);
INSERT INTO `countries` VALUES (138, 'MQ', 'Martinique', NULL, NULL);
INSERT INTO `countries` VALUES (139, 'MR', 'Mauritania', NULL, NULL);
INSERT INTO `countries` VALUES (140, 'MU', 'Mauritius', NULL, NULL);
INSERT INTO `countries` VALUES (141, 'YT', 'Mayotte', NULL, NULL);
INSERT INTO `countries` VALUES (142, 'MX', 'Mexico', NULL, NULL);
INSERT INTO `countries` VALUES (143, 'FM', 'Micronesia, Federated States of', NULL, NULL);
INSERT INTO `countries` VALUES (144, 'MD', 'Moldova, Republic of', NULL, NULL);
INSERT INTO `countries` VALUES (145, 'MC', 'Monaco', NULL, NULL);
INSERT INTO `countries` VALUES (146, 'MN', 'Mongolia', NULL, NULL);
INSERT INTO `countries` VALUES (147, 'MS', 'Montserrat', NULL, NULL);
INSERT INTO `countries` VALUES (148, 'MA', 'Morocco', NULL, NULL);
INSERT INTO `countries` VALUES (149, 'MZ', 'Mozambique', NULL, NULL);
INSERT INTO `countries` VALUES (150, 'MM', 'Myanmar', NULL, NULL);
INSERT INTO `countries` VALUES (151, 'NA', 'Namibia', NULL, NULL);
INSERT INTO `countries` VALUES (152, 'NR', 'Nauru', NULL, NULL);
INSERT INTO `countries` VALUES (153, 'NP', 'Nepal', NULL, NULL);
INSERT INTO `countries` VALUES (154, 'NL', 'Netherlands', NULL, NULL);
INSERT INTO `countries` VALUES (155, 'AN', 'Netherlands Antilles', NULL, NULL);
INSERT INTO `countries` VALUES (156, 'NC', 'New Caledonia', NULL, NULL);
INSERT INTO `countries` VALUES (157, 'NZ', 'New Zealand', NULL, NULL);
INSERT INTO `countries` VALUES (158, 'NI', 'Nicaragua', NULL, NULL);
INSERT INTO `countries` VALUES (159, 'NE', 'Niger', NULL, NULL);
INSERT INTO `countries` VALUES (160, 'NG', 'Nigeria', NULL, NULL);
INSERT INTO `countries` VALUES (161, 'NU', 'Niue', NULL, NULL);
INSERT INTO `countries` VALUES (162, 'NF', 'Norfolk Island', NULL, NULL);
INSERT INTO `countries` VALUES (163, 'MP', 'Northern Mariana Islands', NULL, NULL);
INSERT INTO `countries` VALUES (164, 'NO', 'Norway', NULL, NULL);
INSERT INTO `countries` VALUES (165, 'OM', 'Oman', NULL, NULL);
INSERT INTO `countries` VALUES (166, 'PK', 'Pakistan', NULL, NULL);
INSERT INTO `countries` VALUES (167, 'PW', 'Palau', NULL, NULL);
INSERT INTO `countries` VALUES (168, 'PS', 'Palestinian Territory, Occupied', NULL, NULL);
INSERT INTO `countries` VALUES (169, 'PA', 'Panama', NULL, NULL);
INSERT INTO `countries` VALUES (170, 'PG', 'Papua New Guinea', NULL, NULL);
INSERT INTO `countries` VALUES (171, 'PY', 'Paraguay', NULL, NULL);
INSERT INTO `countries` VALUES (172, 'PE', 'Peru', NULL, NULL);
INSERT INTO `countries` VALUES (173, 'PH', 'Philippines', NULL, NULL);
INSERT INTO `countries` VALUES (174, 'PN', 'Pitcairn', NULL, NULL);
INSERT INTO `countries` VALUES (175, 'PL', 'Poland', NULL, NULL);
INSERT INTO `countries` VALUES (176, 'PT', 'Portugal', NULL, NULL);
INSERT INTO `countries` VALUES (177, 'PR', 'Puerto Rico', NULL, NULL);
INSERT INTO `countries` VALUES (178, 'QA', 'Qatar', NULL, NULL);
INSERT INTO `countries` VALUES (179, 'RE', 'Reunion', NULL, NULL);
INSERT INTO `countries` VALUES (180, 'RO', 'Romania', NULL, NULL);
INSERT INTO `countries` VALUES (181, 'RU', 'Russian Federation', NULL, NULL);
INSERT INTO `countries` VALUES (182, 'RW', 'RWANDA', NULL, NULL);
INSERT INTO `countries` VALUES (183, 'SH', 'Saint Helena', NULL, NULL);
INSERT INTO `countries` VALUES (184, 'KN', 'Saint Kitts and Nevis', NULL, NULL);
INSERT INTO `countries` VALUES (185, 'LC', 'Saint Lucia', NULL, NULL);
INSERT INTO `countries` VALUES (186, 'PM', 'Saint Pierre and Miquelon', NULL, NULL);
INSERT INTO `countries` VALUES (187, 'VC', 'Saint Vincent and the Grenadines', NULL, NULL);
INSERT INTO `countries` VALUES (188, 'WS', 'Samoa', NULL, NULL);
INSERT INTO `countries` VALUES (189, 'SM', 'San Marino', NULL, NULL);
INSERT INTO `countries` VALUES (190, 'ST', 'Sao Tome and Principe', NULL, NULL);
INSERT INTO `countries` VALUES (191, 'SA', 'Saudi Arabia', NULL, NULL);
INSERT INTO `countries` VALUES (192, 'SN', 'Senegal', NULL, NULL);
INSERT INTO `countries` VALUES (193, 'CS', 'Serbia and Montenegro', NULL, NULL);
INSERT INTO `countries` VALUES (194, 'SC', 'Seychelles', NULL, NULL);
INSERT INTO `countries` VALUES (195, 'SL', 'Sierra Leone', NULL, NULL);
INSERT INTO `countries` VALUES (196, 'SG', 'Singapore', NULL, NULL);
INSERT INTO `countries` VALUES (197, 'SK', 'Slovakia', NULL, NULL);
INSERT INTO `countries` VALUES (198, 'SI', 'Slovenia', NULL, NULL);
INSERT INTO `countries` VALUES (199, 'SB', 'Solomon Islands', NULL, NULL);
INSERT INTO `countries` VALUES (200, 'SO', 'Somalia', NULL, NULL);
INSERT INTO `countries` VALUES (201, 'ZA', 'South Africa', NULL, NULL);
INSERT INTO `countries` VALUES (202, 'GS', 'South Georgia and the South Sandwich Islands', NULL, NULL);
INSERT INTO `countries` VALUES (203, 'ES', 'Spain', NULL, NULL);
INSERT INTO `countries` VALUES (204, 'LK', 'Sri Lanka', NULL, NULL);
INSERT INTO `countries` VALUES (205, 'SD', 'Sudan', NULL, NULL);
INSERT INTO `countries` VALUES (206, 'SR', 'Suriname', NULL, NULL);
INSERT INTO `countries` VALUES (207, 'SJ', 'Svalbard and Jan Mayen', NULL, NULL);
INSERT INTO `countries` VALUES (208, 'SZ', 'Swaziland', NULL, NULL);
INSERT INTO `countries` VALUES (209, 'SE', 'Sweden', NULL, NULL);
INSERT INTO `countries` VALUES (210, 'CH', 'Switzerland', NULL, NULL);
INSERT INTO `countries` VALUES (211, 'SY', 'Syrian Arab Republic', NULL, NULL);
INSERT INTO `countries` VALUES (212, 'TW', 'Taiwan, Province of China', NULL, NULL);
INSERT INTO `countries` VALUES (213, 'TJ', 'Tajikistan', NULL, NULL);
INSERT INTO `countries` VALUES (214, 'TZ', 'Tanzania, United Republic of', NULL, NULL);
INSERT INTO `countries` VALUES (215, 'TH', 'Thailand', NULL, NULL);
INSERT INTO `countries` VALUES (216, 'TL', 'Timor-Leste', NULL, NULL);
INSERT INTO `countries` VALUES (217, 'TG', 'Togo', NULL, NULL);
INSERT INTO `countries` VALUES (218, 'TK', 'Tokelau', NULL, NULL);
INSERT INTO `countries` VALUES (219, 'TO', 'Tonga', NULL, NULL);
INSERT INTO `countries` VALUES (220, 'TT', 'Trinidad and Tobago', NULL, NULL);
INSERT INTO `countries` VALUES (221, 'TN', 'Tunisia', NULL, NULL);
INSERT INTO `countries` VALUES (222, 'TR', 'Turkey', NULL, NULL);
INSERT INTO `countries` VALUES (223, 'TM', 'Turkmenistan', NULL, NULL);
INSERT INTO `countries` VALUES (224, 'TC', 'Turks and Caicos Islands', NULL, NULL);
INSERT INTO `countries` VALUES (225, 'TV', 'Tuvalu', NULL, NULL);
INSERT INTO `countries` VALUES (226, 'UG', 'Uganda', NULL, NULL);
INSERT INTO `countries` VALUES (227, 'UA', 'Ukraine', NULL, NULL);
INSERT INTO `countries` VALUES (228, 'AE', 'United Arab Emirates', NULL, NULL);
INSERT INTO `countries` VALUES (229, 'GB', 'United Kingdom', NULL, NULL);
INSERT INTO `countries` VALUES (230, 'US', 'United States', NULL, NULL);
INSERT INTO `countries` VALUES (231, 'UM', 'United States Minor Outlying Islands', NULL, NULL);
INSERT INTO `countries` VALUES (232, 'UY', 'Uruguay', NULL, NULL);
INSERT INTO `countries` VALUES (233, 'UZ', 'Uzbekistan', NULL, NULL);
INSERT INTO `countries` VALUES (234, 'VU', 'Vanuatu', NULL, NULL);
INSERT INTO `countries` VALUES (235, 'VE', 'Venezuela', NULL, NULL);
INSERT INTO `countries` VALUES (236, 'VN', 'Viet Nam', NULL, NULL);
INSERT INTO `countries` VALUES (237, 'VG', 'Virgin Islands, British', NULL, NULL);
INSERT INTO `countries` VALUES (238, 'VI', 'Virgin Islands, U.S.', NULL, NULL);
INSERT INTO `countries` VALUES (239, 'WF', 'Wallis and Futuna', NULL, NULL);
INSERT INTO `countries` VALUES (240, 'EH', 'Western Sahara', NULL, NULL);
INSERT INTO `countries` VALUES (241, 'YE', 'Yemen', NULL, NULL);
INSERT INTO `countries` VALUES (242, 'ZM', 'Zambia', NULL, NULL);
INSERT INTO `countries` VALUES (243, 'ZW', 'Zimbabwe', NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
