
INSERT INTO `documents` VALUES (1, 'Passport', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (2, 'Seaman\'s Book', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (3, 'SRC', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (4, 'FSMB', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (5, 'Medical', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (6, 'PDOS', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (7, 'OEC', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (8, 'Philippine License', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (9, 'UK Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (10, 'US Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (11, 'Electronic Receipt', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (12, 'OTB', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (13, 'NL Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (14, 'Chinese Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (15, 'Schengen Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (16, 'Entry permit (solomon islands)', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (17, 'Bulgarian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (18, 'Bahamas Seaman\'s Book', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (19, 'Indian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (20, 'Brazilian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (21, 'Canadian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (22, 'Nigerian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (23, 'Argentine Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (24, 'Australian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (25, 'Working Permit', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (26, 'UAE Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (27, 'Chilean visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (28, 'Working Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (29, 'Kuwait Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (30, 'Cuban Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (31, 'Qatar Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (32, 'OWWA ', 2, 90, NULL, NULL);
INSERT INTO `documents` VALUES (33, 'Crew ERS# (SBECS)', 2, 0, NULL, NULL);
INSERT INTO `documents` VALUES (34, 'ER#', 2, 0, NULL, NULL);
INSERT INTO `documents` VALUES (35, 'Pre Departure Orientation Seminar', 2, 0, NULL, NULL);
INSERT INTO `documents` VALUES (36, 'Russian Visa', 2, 60, NULL, NULL);
INSERT INTO `documents` VALUES (37, 'Panama Seamans Book', 2, 0, NULL, NULL);
INSERT INTO `documents` VALUES (38, 'Schengen Visa 2', 2, 0, NULL, NULL);
INSERT INTO `documents` VALUES (39, 'SID', 2, 0, NULL, NULL);
