
INSERT INTO `licenses` VALUES (1, 'Panama', 'PANAMA', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (2, 'PRC License', 'PRC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (3, 'Belize', 'BELIZE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (4, 'Antigua and Barbuda', 'ANTBAR', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (5, 'Dutch STCW', 'DSTCW', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (6, 'Chief Engineer', 'E1', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (7, 'Second Engineer', 'E2', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (8, 'OIC Engineering Watch', 'E3', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (9, 'Fourth Engineer', 'E4', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (10, 'Master', 'D1', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (11, 'Chief Mate', 'D2', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (12, 'OIC Navigational Watch Endorsement', 'OIC-NW E', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (13, 'Third Mate', 'D4', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (14, 'Dutch Law Module', 'DLM', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (15, 'Dutch Seaman\'s Book', 'DSB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (16, 'Philippine License', 'Phil Lic', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (17, 'Isle of Man Endorsement and Certificate', 'IOM EC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (18, 'Dutch Form', 'DF', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (19, 'Endorsement of Certificate', 'EC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (20, 'Finnish Endorsement', 'FIN', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (21, 'Tuvalu Endorsement ', 'TCOE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (22, 'Tuvalu Seaman\'s Book', 'TSMB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (23, 'Netherlands Antilles Endorsement', 'NAE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (24, 'PRC OIC Endorsement', 'PRCOE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (25, 'PRC OIC Certificate', 'PRCOC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (26, 'Panama Seaman\'s Book', 'PSMB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (27, 'Panama Endorsement', 'PENDOR', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (28, 'Curacao Endorsement', 'CUR', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (29, 'Curacao Seaman\'s Book', 'CSB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (30, 'PRC Certificate', 'PRCC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (31, 'PRC Endorsement', 'PRCE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (32, 'Pilot Norwegian Exemption', 'PNE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (33, 'Pilot Norwegian License', 'PNL', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (34, 'Antigua and Barbuda Seaman\'s Book', 'ABSMB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (35, 'St. Kitts and Nevis Endorsement', 'SKAN', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (36, 'CPE - Endorsement', 'CPE - En', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (37, 'Registered Master Electrician', 'RME', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (38, 'Bahamas Seaman\'s Book', 'BSB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (39, 'Bahamas Endorsement', 'BE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (40, 'Bahamas GOC ', 'BG', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (41, 'Chief Officer', 'CO', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (42, 'Continous Discharge Certificate', 'CDC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (43, 'Vanuatu Seaman\'s Book', 'VSB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (44, 'Panama CRA', 'CRA', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (45, 'GMDSS Radio Officer (General Operator Certificate)', 'GMDSS', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (46, 'Ship Security Officer', 'SSO', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (47, 'Cyprus SIRB', 'CSIRB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (48, 'Dynamic Positioning Watchkeeping Log Book', 'DP Log B', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (49, 'non-EU/EEA Master Certificate of Competency', 'RTK Lice', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (50, 'Malta Endorsement', 'MEC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (51, ' St. Kitts and Nevis Seamans Book', 'SKANSB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (52, 'RTK License', 'RTK', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (53, 'Gibraltar CRA', 'GCRA', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (54, 'Antigua and Barbuda Endorsement', 'ABE', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (55, 'Antigua and Barbuda GOC', 'ABG', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (56, 'Antigua and Barbuda Endorsement for SSO', 'ABES', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (57, 'CRA', 'CRA', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (58, 'Belize endorsement', 'BLZ', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (59, 'Marina License', 'ML', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (60, 'CPE - SSO', 'CPE - SS', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (61, 'Certification & Transmittal', 'Antigua ', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (62, 'SKN CDC', 'SKC CDC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (63, 'CPE - GMDSS', 'GM', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (64, 'Recognition Certificate', 'RC', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (65, 'Marina Certification _ Master', 'MCM', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (66, 'SKN CPE', 'SKN CPE', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (67, 'Liberia Seaman\'s Book', 'LSB', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (68, 'Marshall Island SMB', 'MIS', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (69, 'Dutch Tanker Qualification', 'DTQ', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (70, 'Electro-technical Officer Certificate', 'ETO ', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (71, 'Electro-technical Officer Endorsement', 'ETO-En', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (72, 'OIC Navigational Watch Certificate', 'OIC-NW C', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (73, 'Faroese Maritime Legislation', 'FML', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (74, 'Antigua and Barbuda Booklet', 'ABB', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (75, 'CRA - Tanker Qualification', 'CRA TQ', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (76, 'CRA - Certificate ', 'CRA ', 60, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (77, 'Marina (certificate)', 'MCer', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (78, 'Marina (endorsement)', 'MEnd', 0, 2, NULL, NULL);
INSERT INTO `licenses` VALUES (79, 'Marina (GOC)', 'MGoc', 0, 2, NULL, NULL);
