
INSERT INTO `medical_certificates` VALUES (1, 'Physical Examination Certificate', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (2, 'Dutch Form', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (3, 'Belize', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (4, 'Panama', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (5, 'Antigua and Barbuda', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (6, 'Drug and alcohol test', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (7, 'Blood Contamination Test', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (8, 'Yellow Fever Vaccine', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (9, 'Typhoid', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (10, 'Cholera', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (11, 'PEME', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (12, 'Pre-Employment Medical Examination', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (13, 'MCA', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (14, 'Seabased Form', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (15, 'Yangon Medical', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (16, 'Tuvalu', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (17, 'Finnish Medical', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (18, 'Malta', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (19, 'UKOOA Medical', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (20, 'Vanuatu Medical', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (21, 'Norwegian', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (22, 'Faroe Form', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (23, 'Medical Exemption', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (24, 'Danish', 60, 2, NULL, NULL);
INSERT INTO `medical_certificates` VALUES (25, 'Bahamas', 60, 2, NULL, NULL);
