
INSERT INTO `training_centers` VALUES (1, 'ABC INSTITUTION', 'INSTITUTION-001', 'Pasay', '456-2345', 'Leah Catigbac', 'institution remarks', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (2, 'Consolidated Training Center', 'CONSO', '4/F S&L Building 1500 Roxas Blvd Manila', '5240572', 'Stefanie ', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (3, 'Far East Maritime Foundation Inc.', 'FAR EAST', '904 Victoria Building, UN Avenue Ermita Manila', '5262477/5268069', 'Fely Corpuz', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (4, 'The Maritime Training Center of the Philippines', 'MTCP', '3/F GE Antonio Bldg., TM Kalaw Ermita Manila', '5210071/5247909', 'Delia Hicban', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (5, 'University of Cebu', 'UC', 'Alumnos,Mambaling,Cebu City', 'None', 'Atty. Augusto W. Go', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (6, 'Maritime Technological & Allied Services, Inc.', 'MARITAS', 'Rm. 415,Prudential Bank Bldg.,Plaza Lacson,Sta Cruz ,Manila,1003,Philippines', NULL, 'Mr. Celso M. De Guzman Sr.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (7, 'Blue Horizon Maritime Training and Assessment Center, Inc.', 'BHMTCI', 'Blue Horizon Bldg., 357 W. Burke Sts. (Along Escolta St.) Binondo, Manila', '245-9613; 243-3164', 'Rodolfo Reyes', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (8, 'Admiral Maritime Training Institute of the Philippines, Inc.', 'ADMIRAL', '2nd Floor,Equitable PCI Bank Building,377 Plaza Sta Cruz,Metro Manila,Phils.', NULL, 'Ms. Ofelia Sajo Angeles', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (9, 'EXACT', 'EXACT', '4F AMSIR Bldg., Paredes cor. Loyola Sts., Sampaloc, Manila (near PRC)', '733-8897; 733-2119; 735-9369', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (10, 'Philippine Nautical Training Institute', 'PNTI', '5th Floor,Intramuros Corporate Plaza,Recoletos St.,', '731-7862/731-7862', 'Ms. Sheen', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (11, 'Pentagon Maritime Foundation Inc.', 'PENTAGON', '7th Roman Santos Bldg., Plaza Lacson, Sta. Cruz, Manila', '734-4718', 'Edward King', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (12, 'Lydia Marine Training Center', 'LYDIA', '1265 Bo. Visaya St., Guadalupe, Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (13, 'Idess Maritime Centre Inc.', 'IDESS', 'Nabasan Pier, Naval Magazine Area, Subic Bay - Freeport', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (14, 'Phil. Asia Trade Testing Center', 'PATTC', '2389 Tejeron St., Sta. Ana, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (15, 'Philippine Seafarers Training Center', 'PSTC', '938 Arlegui St. cor Aguila St.,Quiapo,Manila,Philippines', '734-1651;734-88-98', 'Percival G. Andres', 'Training Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (16, 'Oceanwide Crew Manila, Inc.', 'OCM', '4/F Paseo de Roxas Bldg., Paseo de Roxas cor Legaspi St., Makati City', NULL, 'Linds Boughton', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (17, 'Technical Education and Skills Development Authority', 'TESDA', 'TESDA, Taguig City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (18, 'Maritime Institute of Technology', 'MIT', 'Bañadero, Ozamis City, Philippines', '521-2890', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (19, 'Albatros Foundation Academy', 'AFA', '3rd Flr. 20th Century Mandaluyong City', '533-9189 ; 599-9117', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (20, 'Global Training Systems-Philippines, Inc.', 'GTSPI', 'Suite 205-A,FEMII Annex Building,Andres Soriano Avenue,Intramuros,1002,Manila Ph', '63 2 522-3336', 'Capt. Jesse B. Martinez,MM', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (21, 'Fame Maritime Foundation,Inc.', 'FMFI', 'Ermita Center Building,1350 Roxas Blvd.,Ermita,Manila', NULL, 'Vicente F. Aldanese Jr. (President)', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (22, 'NYK-Fil Maritime E-Training, Inc.', 'NFMTI', 'Gen. Luna cor. Sta. Potenciana Sts., Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (23, 'Protect Marine Deck and Engine Officer of the Phil.,Inc.', 'PMDEP', 'Rm 205/209,BF Condominium Bldg.,Andres Soriano Ave. cor. Solano St.,Intramuros', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (24, 'St. Therese - MTC Colleges - Tigbauan Training Center', 'MTC College', 'Brgy. Tan Pael, 5021 Tigbauan Iloilo', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (25, 'National Maritime Polytechnic', 'NMP', 'Cabalawan,Tacloban City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (26, 'New Simulator Center of the Philippines, Inc.', 'NSCPI', '5th Flr 2053 Building, Ediso St., Makati City, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (27, 'Amosup Seaman\'s Training Center', 'ASTC', 'Kamaya Pt., Brgy. ALas-asin, Mariveles, Bataan', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (28, 'John B. Lacson Foundation, Inc.', 'JBLFI', 'M.H. del Pilar Street Molo, Iloilo City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (29, 'Keel Marine Technologies, Inc', 'K Marine', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (30, 'Maritime Training Center - University of The Visayas', 'MTC-UV', 'Punta Engaño, Lapu-lapu City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (31, 'Sea Quest Maritime Training, Inc.', 'SQMTI', 'Mezzanine B&C, M.F. Tiaoqui Bldg., Plaza Sta. Cruz, Manila', '7355202', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (32, 'Netherlands Shipping Training Centre Foundation, Inc.', 'NSTC', 'Evangelista Street, Palompon Leyte', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (33, 'International Maritime Training Foundation, Inc.', 'IMTFI', '1/F Rm 102, Bel-Air Apts., 1020 Roxas Blvd., Manila', '400-8969/400-5760', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (34, 'Sharp Maritime Security Training Services, Inc.', 'SMSTSI', 'Rm 216, B.F. Condominium, A. Soriano Ave., Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (35, 'Southern Institute of Maritime Studies', 'SIMS', '3/F Heritage Bldg., E. Aguinaldo Highway, Niog, Bacoor, Cavite', '(046)5021614', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (36, 'National Telecommunications Commission', 'NTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (37, 'Intership Navigation Training Center, Inc.', 'INTCI', '2/F CRI Bldg., 665 Pres. Quirino Ave., Malate, Manila', '522-3477', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (38, 'Conautic Maritime Inc.', 'CMI', 'Suite 312/313,Penthouse,Ermita Center Bldg. # 1350 Roxas Blvd.,Ermita,Manila,', '+63 2 5280409', 'Mr. Laurentino G. Saracho', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (39, 'Don Bosco Youth Center', 'DBYC', 'Tondo,Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (40, 'MARINERS Polytechnic Training Center', 'MPTC', '3rd Flr., Ganar Bldg., 2241 Taft Avenue, Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (41, 'Professional Regulation Commission', 'PRC', 'P. Paredes St., corner N. Reyes St., Sampaloc, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (42, 'OFSI Services,Inc.', 'OFSI', '3rd Flr. OFSI,Cabildo cor. Urdaneta Sts,Intramuros,Manila,Philippines', '301-0180', 'Ernesto D. Tagle', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (43, 'Magsaysay Training Center', 'MTC', '6th Floor TIMES Plaza Bldg. U.N. Ave. cor. Taft Ave. Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (44, 'Oceanic Maritime Training Center', 'OMTC', 'Rm. 601,Ermita Bldg.Arquiza cor Alhambra St.,Ermita,Manila', '524-5781;', 'Joyce DC Banares', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (45, 'Asia Pacific Maritime Services, Inc.', 'APMSI', 'Suite 402-403 Ermita Center Building, 1350 Roxas Blvd, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (46, 'Zamboanga Maritime Training Center, Inc.', 'ZMTCI', '#10 Normal Road fronting WMSU, ZC', '(062) 992-5765', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (47, 'Maritime Training Council', 'MTC-NAC', '6th Flr. Blas Ople Bldg,.POEA ', NULL, 'Noriel P. Devanadera', 'NAC', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (48, 'SMTC Global', 'SMTC', 'Polymarina Singapore Maritime Academy', '+65 6873 0304', NULL, 'Polymarina Singapore Maritime Academy, Singapore Polytechnic, 50, West Coast Ferry Road, Singapore, 126980', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (49, 'Isle of Man Ship Registry', 'IOM', 'Peregrine House,Peel Road,Douglas,Isle of Man,IM1,5EH,British Isles', '+44 1624 688500', 'Ron Strathdee (Principal Surveyor Standards)', 'Isle of Man Endorsement', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (50, 'Shipping of Maritime Affairs', 'SMA', 'Willemstad', NULL, 'O. Windster', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (51, 'PROFOUND - MASTER', 'PROFM', 'G/F NFWC Bldg., No. 958 Escoda St., Ermita, Manila', '0', 'Ma. Nida Felmar A. Alquitran', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (52, 'National Telecommunications Comminsion', 'GOC NTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (53, 'Marlow Navigation Training Center Manila', 'MNTC', 'Rm. 403 LBH Bldg 1431 A. Mabini St. Ermita Manila', '63 (2) 4009943', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (54, 'MTC College', 'MTCC', 'Tigbauan, Iloilo', NULL, 'Atty. Arturo A. Sebastian', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (55, 'Misamis Institute of Technology - Maritime Training Center', 'MITMTC', 'Bañadero, Ozamis City', NULL, 'Capt. Rene A. Maglasang', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (56, 'Visayan Maritime Academy Training Center', 'VISMAC', 'Bacolod City', '034-444-1588/444-2491', 'Merigene Y. Regalado', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (57, 'Roger Hart & Associates', 'RHA', 'Qatar', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (58, 'Abacast Training Center', 'ATC', '4th Floor, Enriqueta Bldg. II, Gen. Elias Topacio St., Brgy I, Imus, Cavite', '046-4712215', 'Mr. Victor R. Cataneda', 'Managing Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (59, 'Grand Training Center for Tourism', 'GTCT', 'Philippine Village Hotel', '0', 'Carlos B. Garcia Jr.', 'Group Training Manager', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (60, 'Eurest', 'EUR', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (61, 'MDP Ship Maritime Training Center', 'MDP', 'Suite 610 Ermita Center Bldg., 1350 Roxas Blvd., Ermita, Manila', '0', 'C/E Macario E. Dela Peña', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (62, 'Seagull', 'Seagull', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (63, 'Videotel', 'VIDEOTEL', '84 Newman St. London W1T 3EU,UK', '+44 0 20 7299 1800', 'Barbara Steinberg', 'SSO  Training Center,UK.', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (64, 'C.S.M. Management Services and Consultancy', 'C.S.M.M.S.C.', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (65, 'Meridian Training Center', 'MERI', 'Room 806, 8th Flr., T.M. Kalaw Center Bldg., 667 Kalaw St., Ermita, Manila', '0', 'Marlene Dado Jante', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (66, 'ISM and Quality Systems Inc.', 'ISMQ', 'RECRAA Bldg., Vitalez Compound, Sucat Road, Parañaque City, Metro Manila', '0', 'Milagros G. Agda', 'IQSI Manager', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (67, 'DMMA College of Southern Philippines', 'DMMACSP', 'Tigatto Road, Buhangin, Davao City, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (68, 'Maya Kitchen Culinary Arts Center', 'MAYA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (69, 'Asian Institute of Culinary Arts', 'AICA', 'No. 68, Sen Gil Puyat Avenue, Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (70, 'Center For Multicultural Studies,Inc.', 'CMSI', 'DCL House 4/F 2598 Manchas St.,Brgy Sta Cruz,Makati City,Philippines', NULL, 'Rene E. Cristobal', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (71, 'FMFI Maritime Foundation, Inc.', 'FMFIM', '3/F Coherco Corporate Center, 116 V.A. Rufino St., Legaspi Village, Makati City', '0', 'Mr. Michael J. Estaniel', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (72, 'Phil-Asia Technical Consultant and General Services,Inc.', 'PHIL-ASIA', '2389 Tejeron St.,Sta. Ana,Metro,Manila,Philippines', '563-11-44/564-19-56', 'Augusto T. Peres ', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (73, 'Norwegian Training Center - Manila', 'NTCM', 'Gate 2, NTC-M Building, TESDA Complex, Esst Service Road Taguig Metro Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (74, 'Norwegian Cruise Lines', 'NCL', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (75, 'Orophil Shipping Int\'l. Co., Inc.', 'OROPHIL', 'Knights of Rizal Bldg. A. Bonifacio Drive, Port Area, Manila', '(832) 5270662', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (76, 'SEAMAC International Training Institute, Inc.', 'SEAMAC', 'G/F 867 G. Tolentino St., Sampaloc, Manila', '736-7885', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (77, 'Philippine Merchant Marine Academy', 'PMMA', 'Fort Bonifacio, Metro Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (78, 'Promaritime International Services Corporation', 'PISC', 'SKT Building, Rizal Street, Zamboanga City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (79, 'JCC Review Center and Marine Consultancy Services', 'JCC RCMCS', 'Rm.201 & 404 G. K. Chua Bldg., M. J. Cuenco Ave., Cebu City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (80, 'Alpha Shipmanagement Corporation', 'ASC', '6th Flr. Jemarson Bldg., 1618 Pilar Hidalgo Lim St., Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (81, 'Asian Institute of Maritime Studies', 'AIMS', 'Pasay City, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (82, 'IMMARBE', 'IMM', 'Belize', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (83, 'Fulton Marine International', 'FMI', '1831 Northeast 146th St. ,North Miami,FL 33181', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (84, 'Harbor Training Center,Inc.', 'HTCI', '2/F Harbor Center II Bldg.,Railroad & Chicago Sts.,Port Area (South),1018,Philip', NULL, 'Capt. Alfredo V. Vidal Jr.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (85, 'Maritech Maritime Training Studies and Manning Services, Inc', 'MMTSMSI', '2-3F,CTC Annex Bldg., Pedro Gil St. corner Taft Avenue, Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (86, 'TSM Maritime Training Center', 'TSM', 'Maritime Center Bldg. 1749 Dian Street, Makati City', '860-7500', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (87, 'Athinia Training and Management Services, Inc.', 'ATMSI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (88, 'VMA Global College and Training Center,Inc.', 'VMAG', 'Bacolod City, Philippines', '034-444-1588', 'Dr. Carlitos N. Orola - VP/QMR', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (89, 'Association of Carriers & Equipment Lessors, Inc.', 'ACEL', 'Suite 1601, Jollibee Plaza Condominium, Emerald Avenue, Ortigas, Pasig City', '631-3136', 'Alex Y. Gonzales', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (90, 'Phil. Center for Advanced Maritime Simulation and Training', 'PHILCAMSAT', '2nd Flr.First  Maritime Place,7458 Bagtican St.,SAn Antonio Village,Makati City', NULL, 'C/E Alfredo G. Haboc', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (91, 'Dep\'t of Marine Administration - Myanmar', 'DMA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (92, 'Overseas Workers Welfare Administration', 'OWWA', '7th St., cor FB Harrison St., Pasay City', '891-7601', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (93, 'University of the Visayas Maritime Training Center', 'UVMTC', 'Punta Engano, Lapu-lapu City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (94, 'New Diversified Foundation Inc.', 'NDFI', 'Diversified Corporation Bldg. 707 San Rafael St., Plainview Mandaluyong', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (95, 'Future Culinary Arts Consultancy and Services', 'FCA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (96, 'Occupational Safety Training, Inc.', 'METS', '1209 Tool Drive,New Iberia,LA 70560', '337-365-6595', NULL, 'HUETS', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (97, 'Acadian Integrated Solutions Certificate of Training', 'AISCT', NULL, NULL, 'Will Stallings', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (98, 'MATS College of Technology', 'MATS', 'R. Catillo St.,Agdao,Davao City', NULL, 'Mr. Rolando C. Mabala', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (99, 'International Maritime & Offshore Safety Training Institute', 'DP', '11 th Floor Victoria Bldg.,Unteid nation Avenue,Ermita,Manila,1000 Philippines', '+63 2 302 3168', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (100, 'Oriental Maritime Training Center, Inc.', 'OMTCI', 'Recraa II,Vitales Compound,Sucat,Paranaque,Metro,Manila,Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (101, 'Philippine Center for Advanced Maritime', 'PHILCAMSAT..', '7458 Bagtican St., San Antonio Village, Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (102, 'Blueridge Pacific Institute Inc.', 'BPII', '3rd Floor Manufacturers Bldg., Plaza Sta. Cruz, Metro Manila', '735-17', 'Mr. Rodolfo Reyes', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (103, 'International Development and Environmental Shipping School', 'IDaESS', 'Bldg. 2079 A&B, Nabasan Pier, Naval Magazine Area, Subic Bay Freeport Zone', '63-4702523043', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (104, 'Center For Training Consultancy and Management Services Inc.', 'CTCMI', '2227 Taft Avenue,Malate,Manila', NULL, 'Mrl. Vince I Ison', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (105, 'Pangasinan Merchant Marine Academy', 'PMMA01', 'Perez Blvd., Dagupan City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (106, 'VAA Skills Development & Maritime Training Center, Inc.', 'VSDMTC', 'Rm. 269 Ramagi Bldg., Pedro Gil St., Paco Manila', '523-5960', 'Virginia A. Arao - President', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (107, 'Nova College Maritime Academy', 'NCMA', 'Kanaalstraat 7,1975 BA Ijmuiden,the Netherlands', NULL, 'J.W. Hof', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (108, 'Blessing Eminence Seafarers Training Foundation', 'BESTF', 'Room 100 Mezzanine, Manufacturers Building Inc. Plaza Sta Cruz, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (109, 'Seatech Maritime Training Center', 'SMTC1', 'No. 2635 2/F Manor House, Taft Avenue, Malate, Manila', '+63 2 522-5034', 'Capt. Jesus V. Cabrera, MAME', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (110, 'Chartered Institute of Environmental Health', 'CIEH', 'Chadwick Court, 15 Hatfields, London SE1 8DJ', '020 7827 5800', 'CIEH', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (111, 'Cavite Solas Training Center Co.', 'CSTCC', 'Alima,Bacoor,Cavite,Philippines', NULL, 'capt. Andy R. Domingo', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (112, 'Rich Maritime Training Center', 'RMTC', '2nd Flr.,Monte de Piedad Bldg.,Palza Sta. Cruz,Manila', NULL, 'Marites C. Tolentino', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (113, 'Inter-Seas Management  Training Center Corporation', 'ISMTCC', 'Manila', NULL, 'Crisanto C. Dela Torre', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (114, 'ZRC Training Center Phils. Inc.', 'ZRC', '4/F Rm. 403 Ermita Center Bldg.,Roxas Blvd. cor Sta. Monica St.,Ermita Manila,Ph', '338-9153', 'C/E Gilbert B. Milana', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (115, 'Cervas Culinary Training Center', 'CCTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (116, 'ISLACARE Incorporated', 'ISLA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (117, 'Sandigan Ship Services, Inc.', 'SSSI', 'Legaspi Village, Makati, Philippines', '0', 'Capt. Masahiro Ikeshita', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (118, 'EPSILON Maritime Services, Inc.', 'EPSILON', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (119, 'Southfield Maritime Training Foundation, Inc.', 'SMTFI', '5th Floor VIP Bldg, 1440 Roxas Boulevard, Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (120, 'Sea Merchants, inc.', 'SMI', NULL, NULL, 'Ruby O Jaucian', 'HR Partner', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (121, 'Mariners Consultancy and General Services', 'MCGS', '3/F, NFWC Bldg., Escoda cor San Marcelino Sts., Ermita, Manila', '4042429', 'Carlito P. Miram, Sr.', 'Training Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (122, 'PhilAsia Maritime Services Training Center Inc.', 'PMSTCI', 'Cebu Lioc Kui Bldg,#6 J.L. Briones Avenue,North Reclamation Area,Cebu City,Phils', '032-231-8395', 'Capt. Restituto R. SAblas,MM', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (123, 'Crystal Shipping, Inc.', 'CSI', '3rd Floor Shipping Centre Bldg., 707 A. Soriano Jr. Ave. Intramuros, Manila', '+63 2 5277009 / 5277013', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (124, 'Welding Industries of the Philippines, Inc.', 'WIPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (125, 'Cebu Central Colleges', 'CCC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (126, 'V.Ships', 'VS', '24 Av De Fontvieille, PO Box 639 MC 98013 Monaco Cedex', NULL, 'Capt. Arnold Guia', 'Training Manager', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (127, 'Executive Technical Consultants', 'ETC', '3190 New Panaderos St., Ext., Sta. Ana, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (128, 'Blue Manila Inc.', 'BMI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (129, 'Consolidated Maritime Resources Foundation, Inc.', 'CMRFI', '4/F S&L Building, 1500 Roxas Blvd., Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (130, 'Maritime Academy of Asia and the Pacific - Kamaya Point', 'MAAP', 'Kamaya Pt., Brgy. Alas-asin , Mariveles, Bataan', NULL, 'VADM Eduardo Ma R. Santos, AFP (Ret)', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (131, 'The Maya Kitchen Culinary Arts Center', 'TMKCAC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (132, 'QSU security GbR', 'QSU', 'Hauptstrabe 18a D-22964n Steinburg OT Mollhagen', '+49 (700) 88778801', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (133, 'Maritime Industry Authority', 'Marina', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (134, 'ODFJELL Academy', 'ODA', 'Subic BayFreport Zone, Olongapo City', 'none', 'Capt. Fidel N. Perez', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (135, 'FIL-Trade Inc.', 'FILTRADE', '4259 Emilia cor Filmore Sts., Makati City', '815-3668', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (136, 'Maritech Maritime Training, Studies & Manning Services, Inc.', 'MARITECH', '4th-6th Floors,CTC Commercial Building,P.Gil cor Taft Ave,Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (137, 'Reinier Pacific International Shipping, Inc.', 'RPISI', 'Unit 1201-1204 4th floor Paragon Plaza Condominium 162 EDSA cor. Reliance St. Ma', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (138, 'Global Gateway Crewing Services Inc.', 'GGCSI', '3/F Trans-Phil House, 1177 Chino Roces Ave., Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (139, 'Oriental Shipmanagement Co.,Inc.', 'OSMCI', 'Recraa Bldg.,Vitalez Compound,Sucat Road,Parañaque City,1700 Philippines', '632 825-7956 to 59', 'Capt. Isidro M. Colocado PCGA', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (140, 'Bright Maritime Corporation', 'BMC', '2nd Flr.,Emerald Bldg.,#24 Emerald Ave.,Ortigas Center,Pasig City', NULL, 'Desiree P. Sillar', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (141, 'Gergon Maritime Services Inc.', 'GMSI', '.', '.', '.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (142, 'Maritime Trainings Centrum BV', 'MTC BV', 'Maasvlakte, The Netherlands', NULL, 'R. Moleman', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (143, 'Consolidated Training System, Inc.', 'CTSI', 'Ermita Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (144, 'Servizi Integrati di Sicurezza s.r.l.', 'SIS', 'Via Mare Adriatico 72/E - 65010 Spoltore (PE)', '+39 0854971521', NULL, 'Fax +39 085 4973121\n', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (145, 'Exec Chef Charles Culinary Arts Training Center', 'ECCCATC', 'Rose of Heaven Drive Cor. Tidy Tips st., Talon Village 4 Las Piñas City', '3842745 / 5016425', NULL, 'Mobile No. 0927-5976643\nEmail Add: exechefcharpol@yahoo.com', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (146, 'J-Phil Marine Inc.', 'JPMI', '1977 A. Linao St., Malate Metro Manila, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (147, 'Eagle Star', 'ES', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (148, 'Lydia Mar (Manila) Inc.', 'LYDIAM', '9th Floor, G.E. Antonio Bldg, T.M. Kalaw cor J. Bocobo Sts., Ermita, Manila', '0', 'Capt. Jesus P. Boldo', 'no phone number', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (149, '', 'MPPR', '9th Floor, G.E. Antonio Bldg, T.M. Kalaw cor J. Bocobo Sts., Ermita, Manila', '0', 'Capt. Jesus P. Boldo', 'no phone number', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (150, 'Maritime Piracy Preparedness and Response', 'MARPPR', '9th Floor, G.E. Antonio Bldg, T.M. Kalaw cor J. Bocobo Sts., Ermita, Manila', '0', 'Capt. Jesus P. Boldo', 'no phone number', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (151, 'Oilwell Drilling Technology Development Center Inc.', 'ODTDC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (152, 'MFI Foundation, Incorporated', 'MFI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (153, 'Technology & Livelihood Resource Center - Office of the Pres', 'TLRR', 'Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (154, 'SETAMS Training Center', 'SETAMS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (155, 'Simulator Center of The Philippines, Inc.', 'SCTPI', '5th Floor 2053 Building, Edison St., Makati City, Philippines', '0', 'Capt. Cesar A. Nerpio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (156, 'Compass', 'COMP', '1913 Luna Orosa Bldg., Taft Avenue, Malate, Manila', '0', 'Dakila P. Villanueva', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (157, 'National Quarantine Office', 'NQO', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (158, 'Skippers United Pacific Inc.', 'SUPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (159, 'Britannia Training Center Inc.', 'BTCI', 'Suite 601 Ortigas Building, Ortigas Avenue, Pasig City', '9140571-72', NULL, 'E-mail: britannia@globelines.com.ph\nFax: 9140573\n', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (160, 'The Marine Engineer Officers Association of the Philippines', 'MEOAP', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (161, 'Technological Institute of the Philippines', 'TIP', '363 P.Casal St., Quiapo, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (162, 'Eastgate Maritime Training Center,Inc.', 'EMTCI', '4th Flr. Eastgate Center,169 EDSA,mandaluyong City', NULL, 'CApt. Emmanuel L. Regio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (163, 'Island Overseas Transport Corporation', 'IOTC', '2nd Flr.,Easgate Center,169 EDSA,Mandaluyong City,Philippines', '5336101', 'Capt. Emmauel L. Regio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (164, 'Jotun', 'JT', NULL, NULL, 'Tony Chioh', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (165, 'Transnational Institute of Learning Corp.', 'TILC', '#50 Transnational Compound Multinational Driv Brgy Sto nino,Paranaque City', NULL, 'Capt. Marcelo R. Raneses', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (166, 'Sea Workforce Manila Corporation', 'SWMC', 'Suite 25 G/F The midland Plaza M. Adriatico St., Ermita ,Manila', '5239496-97', 'Capt. Peter M. Torres', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (167, 'Chef Maritime Management Services', 'CMMS', 'GLC Bldg. T.M. Kalaw Street Cor. A. Mabini Street Ermita Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (168, 'Sparrows Training Centre', 'STC', 'Carlton House, 33 Robert Adam Street, London W1U 3HR', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (169, 'Department of Manpower Development and Placement', 'DMDP', 'Cebu City', '0', 'Ma. Gina A. Yosores', 'OIC Dept. Head', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (170, 'EVIC Human Resourse Mgmt., Inc.', 'EHRMI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (171, 'Pearl Grace Shipmanagement, Inc.', 'PGSI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (172, 'Parola Maritime Agency Corporation', 'PMAC', 'Rm. 104 Phoenix Bldg., Recoletos St., Intramuros,Manila.Phil/', NULL, 'Capt. Christopher Del Rosario', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (173, 'Pacific Ocean Manning, Inc.', 'POMI', '1535 M. Adriatico St., 1000 Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (174, 'TARA Skills Proficiency Center, Inc.', 'TARA', '303 Real St., Pamplona III, Las Piñas City', 'none', 'Capt. Juanito D. Salvatierra Jr.', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (175, 'Korpil Training Center', 'KSMC', '3rd Floor Paragon Tower, #351 A. Flore St., Ermita Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (176, 'Marine Applied Systems Technology Resource Center', 'MAST', '1568A San Marcelino St. Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (177, 'Associated Ship Management', 'ASM', '5/f 665 CRI Bldg.,Quirino Ave. Malate,Manila', '404-2780', 'Maria Rodelita M. Homecillo', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (178, 'Dolphin Ship Management, Inc.', 'DSMI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (179, 'Oceancrew Marine Services, Inc.', 'OMSI', 'Mary Bachrach Bldg. cor. 25th & AC Delgado St. 1018 Port Area, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (180, 'Cebu Reliable and Excellent Seafarers Training Center, Inc.', 'CREST', 'M.J. Cuenco Ave.,corner R. Palma St. Cebu City', NULL, 'Capt. Matias O. Radores Jr.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (181, 'Seacrest Maritime Management, Inc.', 'SMMI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (182, 'Cargo Safeway, Inc.', 'CSI.', 'Seabourne Building 4203 R.Magsaysay Blvd. corner Sociego St. Sta. Mesa, Manila', '714-7337 / 736-0262', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (183, 'Dohle Shipmanagement', 'DS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (184, 'NYK-Fil Ship Management, Inc. Training Center', 'NYK', 'Gen. Luna St. corner Sta. Potenciana St., Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (185, 'Career Philippines Shipmanagement, Inc.', 'CPSI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (186, 'United Philippine Lines Inc.', 'UPL', 'One Fort Santiago Bldg.,Sta. Clara St.,Intramuros,manila', NULL, 'Salvador Marzan', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (187, 'EPIC', 'EPIC', '16/F Ramon Magsaysay Bldg.1680 ROxas Blvd.,Manila', '+63 2 405 3023', 'Capt. Hernando S. Eusebio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (188, 'GPN International Maritime Training Center Inc.', 'GPN', '7th Flr. S&L Building 1500 Roxas Blvd. Ermita, Manila', '527-1069 / 516-2993', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (189, 'Aquarius Maritime Development Center and Consultancy', 'ANDCC', 'Room 201, 2nd Floor, G.K. Chua Bldg. M.J. Cuenco Avenue, Cebu City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (190, 'Wilhemsen-Smith Bell Manning, Inc.', 'WSBM', '3rd & 16th Floor Banco de Oro Plaza, 8737 Paseo de Roxas, Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (191, 'T.R.A.M. Integrated Training Solutions, Inc.', 'TRAM', 'Mezzanine Floor, E.M.I. Center, 665 Pres. Aquino Ave., cor. leveriza St., Malate', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (192, 'Nautical Options Training Institute of the Philippines Inc.', 'NOTIP', '3/f Capitan Pepe Bldg.,C.M. Recto cor Rizal Avenus Sta. Cruz,Manila', '0632 735 6479', 'Nenette J. Saguid', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (193, 'Trans Star Shipping Agency Corp.', 'TSSAC', '11 flr . G.E. Antonino Bldg.,T.M. Kalaw cor J. Bocobo St.s,Ermita,Manila', NULL, 'Capt. Julius Dante B. Tobias', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (194, 'Alster International Shipping Services,Inc.', 'AISSI', '2/F 2053 Building,Edison St.,1234 Makati City,Metro Manila,Philippines', NULL, 'Capt. Felix G. Valenzona', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (195, 'Vestland Maritime Corporation', 'VMC', 'VMC Bldg. 3306 Matanzas St. Palanan Makati City', '+632 5501833', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (196, 'Maunlad Trans, Inc.', 'MTI', 'RTJ Building, 3681 Bautista St. Palanan, Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (197, 'Medbulk Maritime Management Corporation', 'MMMC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (198, 'Univan Management Services Phils., Inc.', 'UMS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (199, 'J&L Maritime Review Center', 'J&L', '6th flr. Rm. 619 Manufacturers Bldg., Plaza Sta. Cruz, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (200, 'Maritime Career Development Center, Inc.', 'MCDC', '3rd Floor (Rm 320-A) Prudential bank Bldg., Plaza Lacson, Sta. Cruz, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (201, 'Training Portal', 'TP', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (202, 'Crossworld Marine Services, Inc.', 'CWMSI', '7Flr. Sage House, 110 V.A Rufino Street, Legaspi Village, Makati City', '750-5268', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (203, 'Bourbon Marine Services Manila', 'BMSM', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (204, 'North Sea Marine Services Corp.', 'NSMSC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (205, 'Sealanes Marine Services, Inc.', 'SMSI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (206, 'Holy Cross of Davao College, Inc.', 'HCDCI', 'Sta. Ana Avenue, Davao City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (207, 'Pearl Grace Shipmanagement,Inc.', 'PGSI.', '1963 F. Agoncillo St., Malate,Manila', '63 2 526 4013', 'Capt. WalfredoC. Rivas Jr.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (208, 'Philippine Transmarine Carrier,Inc.', 'PTC.', 'First Maritime Place,Bagtikan St., San Antonio Village', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (209, 'C.F. Sharp Crew Management, Inc.', 'CFSharp', 'Casa Rocha, 290 General Luna Street, Intramuros, Manila', '5276031', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (210, 'MARINA', 'Marina.', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (211, 'Top Ever Marine Management Philippine Corporations', 'TEMPC', '512 Gen. M.Hizon St.,1929-A CApt. Reyes St., Bangkal,Makati', NULL, 'Capt. Oscar D. Orbeta', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (212, 'Italian Maritime Academy Phils.,Inc.', 'ITMAPI', '6/F NEDA sa Makati Bldg.,106 Amorsolo St.,Legazpi Village,1229 Makati City', '813 5510', 'Capt. Nicolo S. Terrei', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (213, 'Belchem Philippines, Inc.', 'Belchem', 'One Fort Santiago Bldg., Sta. Clara St., Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (214, 'Pacific Ocean Tech,Inc.', 'POTI', 'c/o Suite 1001-B,10-F State Center II,Ortigas Ave.,Mandaluyong City , 1501 ,Phil', NULL, 'Capt. Angela A. Peñalosa', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (215, 'Don Bosco Technology Center', 'DBTC', 'Pleasant Homes Subdivision, Punta Princesa', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (216, 'Sea Express Training and Marine Services Inc.', 'SETAMS.', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (217, 'John B. Lacson Colleges Foundation', 'JBLCF', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (218, 'Singa Ship Manageemnt Phils., Inc.', 'SSMPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (219, 'Ship Hotel Cruise Institute of the Philippines Inc', 'SHCIPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (220, '\"K\" Line Maritime Academy Philippines Inc.', 'KLMAPI', '\"K\" Line Bldg., Coral Way Drive, Central Businees Park 1 Pasay City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (221, 'Misamis Institute of Technology', 'MIT.', 'Bañadero, Ozamiz City, Philippines', '5212890', 'Capt. Rene A. Maglasang', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (222, 'Diamond - H Marine Services & Shipping Agency, Inc.', 'DHM', 'Unit 22-A Chatham House 116 Valero St., cor V.A. Rufino, Makati City', '4034519', 'Rommel Erwin F. Turingan', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (223, 'Manila Ocean Crew Management, Inc.', 'MOC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (224, 'International School for Culinary Arts & Hotel Management', 'ISCAHM', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (225, 'The OBRIENS Group', 'TOG', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (226, 'Notre Dame Oilfields Maritime Services,Inc.', 'NDOMSI', '2400 Palm Court St. F.B. Harrison St., Pasay City', NULL, 'Teresita B. Dipon', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (227, 'Lotus Shipmanagement Inc.', 'LSI', '7 flr S&L Building I,1500 Roxas Blvd., ', '4002189', 'Marianito Z. Aguisanda', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (228, 'Ocean Prosperity Manning and Management Corporation.', 'OPMMC', '2&3 4F Legaspi Towers 300 Roxas Blvd.,Manila', '5212236', 'Zaldy Villafor', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (229, 'Orient Lines', 'OL', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (230, 'NCL', 'NCL.', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (231, 'Allstar Maritime Training Center Inc.', 'ALLSTAR', '3?F de Leon Bldg.,1151 MH Del Pila, Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (232, 'Scanmar Maritime Services, Inc.', 'SMSInc', 'G/F Royal Enterprise Bldg., 2227 Chito Roces Ave.,  Makati City', 'none', 'Ms. Raquel R. Coronado', 'in-house training', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (233, 'Imperial Scanship, Inc.', 'ISI', '18/F Ramon Magsaysay Center 1680 Roxas Blvd., Manila', '303-2621', NULL, 'Fax: 303-2625', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (234, 'National Manpower and Youth Council', 'NMYC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (235, 'NE Plus Ultra Training Center', 'NE', '3rd Floor Shipping Centre Building 707 A.Soriano Jr.Ave. Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (236, 'Manila Evening Vocational School', 'MEVS', 'Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (237, 'Negros Navigation Co., Inc.', 'NNCI', 'Manila', NULL, 'Angelito M. Salvio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (238, 'Kryz Livelihood Training Center, Inc.', 'KLTCI', 'Blk 7 Lot 17 Villa San Paulo, Smbag, Jaro, Iloilo City 5000 Philippines', '+630335084773', 'Cencepcion C. Carillo', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (239, 'International Ship Crewmanagement Phils.,Inc.', 'ISCPI', 'Units N,O & P 28 Floor Burgundy Corporate Tower 252 Sen. G. Puyat Avenue,Makati ', '+63 8560490', 'Ma. Luisa B. Parco', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (240, 'ISNTC Intership Navigation Training Center', 'ISNTC', '2/F CRI Building, 665 Pres. Quirino Avenue, Malate, Manila', '522-3477; 521-9306', NULL, '\n', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (241, 'PNTC Colleges Maritime Training Center', 'PNTC', 'Intramuros Corporate Plaza, Recoletos St., Intramuros, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (242, 'Wallem Maritime Service Inc.', 'WMSI', 'Beaterio and Legaspi Sts.,Intramuros,Manila', NULL, 'Engr. Artemio V. Serafico', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (243, 'Global Overseas Training Institute for Heavy Equipment', 'GOTIHED', '248 B.C. Dela Paz St. Caniogan, Pasig City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (244, 'Bahamas Maritime Authority', 'BMA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (245, 'Unisea Philippines Inc.', 'UPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (246, 'University of Southern Philippines Foundation', 'USPF', 'Salinas Drive,Lahug,Cebu City,Philippines', NULL, 'Alicia P. Cabatingan, Ed. D.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (247, 'Maritime Services & Management, Inc.', 'MSMI', 'MSMI Building, Manila', NULL, 'Capt. Rodolfo D. Estampador', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (248, 'The OSM Group', 'OSM', '479 VP Bldg.,Pedro Gil St., Ermita,Manila', NULL, 'Commodore Adonis B. Donato', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (249, 'Davao Crown Recency', 'DCR', 'J.P. Cabaguio Avenue,Agdao,Davao City', NULL, 'Villamor S. Quebral,ED.D.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (250, 'Deck View Cafe', 'DVC', '6th Floor Champ Bldg., Bonifacio Drive, Port Area, Manila', NULL, 'Rodolfo F. Macaraeg', 'Training Manager', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (251, 'German Marine Agencies,Inc.', 'GMAI', '3912 Lubeca House Hen. makabulos St., Bangkal,Makati City', NULL, 'Capt. Carlos A. Anacta', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (252, 'Senator Crewing (Manila), Inc.', 'SCM', '5/F Hyatt Center Bldg. Ortigas Avenue, Mandaluyong City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (253, 'Asia Pacific Training Center', 'APTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (254, 'Crewserve Inc', 'CreS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (255, 'Pacific Seamen Services, Inc.', 'PSSI', 'Unit 33, 34 & 35, 3rd Floor Columbia Tower.', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (256, 'Aklan Polytechnic Institute', 'API', 'Kalibo, Aklan, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (257, 'Cranmer-Bray Training Center, Inc.', 'CBTCI', 'Manila, Phillipines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (258, 'Sea Power Shipping Enterprises,Inc.', 'SPSE', '2nd & 4th Flr.,Sun Plaza Bldg.,Brgy, Wack wack,Mandaluyong City', '570 92 65', 'mr. Ethelswardo SJ. Raton', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (259, 'Magsaysay Institure of Shipping', 'MIS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (260, 'JORIN Maritime Consultancy Services, Inc.', 'JMCSI', 'Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (261, 'Midocean Shipmanagement Corp.', 'MOSC', 'Makati City', NULL, 'Capt. Bethoven S. Sagun', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (262, 'Columbia Shipmanagement', 'CSMT', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (263, 'Wavelink Maritime International', 'WMI', 'Singapore', NULL, 'Mike Kee Lek Yong', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (264, 'Anglo-Eastern Crew Management Phils., Inc.', 'AECMPI', 'GF & 2F Bloomingdate Building, 205 Salcedo Street, Legaspi Village Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (265, 'KGJS Fleet Management Manila, Inc.', 'KGJSM', '6th to 7th Floor, Rufino Plaza Bldg., 6784 Ayala Ave. ', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (266, 'PRO SEA Marine Education', 'PROSEA', 'P.O. Box428, 3500 AK Utrecht, The Netherlands', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (267, 'AboitizJebsen Crew Management', 'AJCM', '2/F Harbor Center II, Railroad St., South Harbor, Port Area, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (268, 'Lucky Eight Maritime Training & Assessment Center,iNc.', 'LEMTCA', 'Rm 206-208 2/F ,A. Mabini St., Ermita,Manila', '632 310 5281', 'Chef Condrado Bolanio', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (269, 'Holland America Line', 'HAL', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (270, 'Maine Marine Philippines, Inc.', 'MMPI', '17F Ramon Magsaysay Center 1680 Roxas Blvd., Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (271, 'Inter-World Shipping Corporation', 'IWSC', 'Unit B-2 Sinagoga Bldg., 481Sinagoga Street, Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (272, 'Seapreneur Training Center,Inc.', 'STCI', '403 Travellers Life Building 490 T.M. Kalaw,Ermita,Manila,Philippines', '02-4048674', 'Mr/ Rolando T. Dumelod', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (273, 'Great Seas Mariners Training & Assessment Center, Inc.', 'GSM', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (274, 'Leonis Navigation Company, Inc.', 'Leonis', '2nd Floor, Leonis Building, 915 Pres. Quirino Ave. corner Leon Guinto St.,Malate', '523-8646 to 50', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (275, 'Intercrew Philippines Agency Inc.', 'IPAI', 'Unit 202 Marbella II Bldg., 2071 Roxas Blvd., Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (276, 'Maresk-Filipinas Crewing', 'MFC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (277, 'Training Center Phils. Inc.', 'tcpi', 'Rm. 204, 2F, Ermita Center Bldg., Roxas Blvd. cor Sta. Monica St., Ermita Manila', '354-6889; 354-6870', 'C/E Rodelio J. Lagat', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (278, 'Globe Maritime Training Center', 'GMTC', 'Unit 311 BPI Roman Santos Bldg., Plaza Lacson, Sta. Cruz, Manila', '516-3634; 386-7114', 'C/E Gilbert B. Milana', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (279, 'Veritas', 'Veritas', '9th floor, vernida IV bldg., 128 L.P. Levistre St., Salcedo Village, Makati', '553-4709', NULL, 'Fax No.: 840-2000/5534816', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (280, 'Towers Maritime Training Center', 'TMTC', '3/F Annex Building Community Chest Foundation, Inc. ', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (281, 'Delfi Shipping Agency Inc.', 'DSAI', '7th Flr De Leon Center Bldg. 1151- M.H. Del Pilar cor Nuestra Sra De Guia,Ermita', '632 516 3000', 'Sarah Zorayda T. Yadao-Lapaan', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (282, 'Araw Shipping Agency,Incorporated', 'ASAI', '2nd Flr. Palacio Grande Bldg., Gen. Luna cor Anda St.,Intramuros,Manila,Philippi', '5270772', 'Allen G. Gascon', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (283, 'Surigao Education Center Maritime Training Center', 'SECMTC', 'Km.2, Surigao City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (284, 'Spliethoff Group Manila, Inc.', 'SGMI', '39th Floor,Rufino Pacific Tower 6784 Ayala Ave.,cor V.A. Rufino St.Legaspi Vill.', '+63 2 3046 911', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (285, 'SAM Electronics Nederland B.V.', 'SAM', 'P.O. Box 5115, 3008 AC Rotterdam Harbour 1093, The Netherlands', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (286, 'Korea-Philippines Vocational Training Center', 'KPVTC', 'Buhisan, Tibungco, Davao City', 'N/A', 'Egmedio O. Valdez Jr.', 'Center Administrator', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (287, 'Tonsberg International Training Center,Inc.', 'TITCI', 'Rm 914 9th Fl.,Manufacturers Building Inc.,Plaza Sta Cruz,Manila', '708-9936', 'Ana R. Fernandez', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (288, 'BSM Maritime Training Center', 'BSMMTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (289, 'Seapreneur Training Center, Inc.', 'SPCTI', '403 Travellers Life Building 490 T.M. Kalaw, Ermita, Manila', '3542956', 'Mrs. Rowena A. Balane', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (290, 'Sunbright Maritime Services,Inc.', 'SMS', '2F 815 Remedios St., Malate,Manila,Philippines', '0063 2 4501812', 'Floro Cruz L. Losbañes', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (291, 'Seabase Training Center for Watchkeeping,Inc.', 'STCWI', '11th Flr G.E. Antonino Bldg.,T.M. Kalaw St., corner J. Bocobo St.,Ermita,Manila', NULL, 'Capt. Lennie B. Arroyo', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (292, 'Amtek Consulting The Reliable  Alternative', 'ACTRA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (293, 'Philands Training School Inc.', 'PTSI', 'Room 308 3rd Flr. BPI Roman Santos Bldg., Plaza Lacson, Sta. Cruz, Manila', '+6325221391', 'Mr. Eriberto R. Ruiz', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (294, 'Mariana Maritime Center Inc.', 'MMCI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (295, '1022 Maritime Services, Inc.', 'MSI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (296, 'Crewcare, Inc.', 'CI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (297, 'Nautilus Pacific Maritime Training Center Inc.', 'NPMTCI', '2nd Flr Metro Bank,Ermita Center Bldg., # 1149 A. Mabini St. cor A. Flores St.', NULL, 'Mr. Alejandro L. Palanca', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (298, 'Maersk Training', 'MT', 'Maersk Training Svendborg A/S', NULL, 'Didde Bielefeldt-Petersen', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (299, 'Agemar Manning Agency, Inc.', 'AMAI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (300, 'Polaris Centre', 'PC', 'Rm 35 3rd Flr., San Luis Bldg.,Ma Orosa cor. T.M. Kalaw,Ermita,Manila', '0917-6658127', 'Capt. Merardo M. Galera', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (301, 'Seabase Training Center for Watchkeeping, Inc.', 'STCW', '11th & 12th Flir. G.E. Antonio Bldg., T.M. Kalaw St. corner J. Bocobo St.', NULL, 'Mr. Guy Domino A. Macapayag', 'Ermita, Manila', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (302, 'Ban-Uden Crewing, Inc.', 'BUCI', '40 Faith Street., Project 6, Quezon City', '927-4696', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (303, 'Century Maritime Agencies Inc.', 'CENMAR', '505-507 VIP Bldg., 1140 Roxas Blvd. Ermita, Manila', '524-3173 Fax: 25243196', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (304, 'd\'AMICO SHIP ISHIMA PHILIPPINES INC.', 'DSIPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (305, 'De Minister Van Infrastructuur En Milieu', 'DMVI', 'The Netherlands', NULL, 'J.P. Bijkerk', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (306, 'The Minister Van Infrastructuur En Milieu', 'TMVI', 'The Netherlands', NULL, 'J.P. Bijkerk', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (307, 'Equal Marine International Inc.', 'EMIIN', 'Paco, Manila,Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (308, 'Safebridge Gmbh', 'Safe Gmbh', NULL, '+49-40-55565791-0', NULL, 'Hammerbrookstr. 89,20097 Hamburg, Germany', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (309, 'Falck Safety Services Den Oever', 'FSSDO', 'Den Oever', NULL, 'A.J. Herfkens', 'OPITO Approved', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (310, 'International Maritime Training Centre', 'IMTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (311, 'Stolt-Nielsen Philippines, Inc.', 'SNPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (312, 'VMA Global College', 'VMAGC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (313, 'POS-FIL MTC Corporation', 'PFMC', '5th Flr-Jemarsons Place,1626 P. Hidalgo Lim St.,Malate,Manila', '302-7157', 'Ms. Marielle M. Tibayan', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (314, 'Philippines Japan Maritime Training Management Inc.', 'PJMTMI', '10th floor MARC 2000 Tower 1973 Taft Ave. Malate, Manila', '+6324508995', NULL, 'Email: pjmtm2012@gmail.com', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (315, 'Avior Marine Inc.', 'AMI', '2/F UPRC I Bldg., 2230 Chino Roces Ave., Makati City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (316, 'European Training & Competence Centre Inc.', 'ETCCI', '6-7Flr Dohle Haus Manila 30-38 Gil Puyat Ave.cor. Bautista St.,Brgy.San  Isidro', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (317, 'Renaissance Training Center, Inc.', 'RTCI', '3713 Bautista St. Palanan Makati City, Metro Manila', '836-7387', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (318, 'Seamaster Shipmanagement Corporation', 'SSC', 'Unit 401 U.N. Square Building, U.N. Avenue cor Jorge Bocobo St., Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (319, 'PB Maritime Personnel, Inc.', 'PBMPI', '16/F Magsaysay Center, 1680 Roxas Boulevard, Manila 1000', '+632 405 3023', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (320, 'JDA Interphil Maritime Services Corp.', 'JDA Inter', 'Room 402, 403 and 404, Fourth Floor, GLC Building', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (321, 'Asia Institute of Management', 'AIM', 'Manila', NULL, 'Ms. Marietta C. Ramos', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (322, 'V. Catering Culinary Training Centre', 'VCCTC', '1535 M.Adriatico St.,Ermita,Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (323, 'Northstar Training and Consultancy,Inc.', 'NTCI', 'Suite C,11th Flr G.E. Antonino Bldg.,TM Kalaw and J. Bocobo Sts.', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (324, 'Sandigan Maritime Training, Inc.', 'SMTI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (325, 'PROFOUND-MASTER', 'PFMSTR', 'G/F NFWC Bldg, No.958 Escoda St., Ermita, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (326, 'FSC Training Center Inc.', 'FTCI', 'FSC Training Center Bldg., 2086 Madre Ignacia St., Malate, Manila', '5265711', 'Mr. Joseph R. Ferrer', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (327, 'DeltaMeco Crewing Services Inc.', 'DMCSI', 'Unit 310 & 311 Vareb Mansion, 1679 A. Mabini St., Malate, Manila, Philippines', '+6325267855', 'Capt. Igmedio G. Sorrera', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (328, 'Commodore Maritime Study & Training Center Foundation, Inc.', 'CMSTCFI', 'Rm.704, Prudential Bank Bldg., Plaza Lacson, Sta. Cruz, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (329, 'Transorient Maritime Agencies Inc', 'TMAI', 'Transorient Maritime Bldg. II, 1438 Agoncillo St., Ermita,Manila', NULL, 'Ma. Caroline V. Toledo', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (330, 'United Seafarers Foundation of the Philippines, Inc.', 'USFPI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (331, 'Center for Knowledge and Advance Training', 'CKAT', 'Unit 611 S&L Building 1500 Roxas Blvd. Cor. R. Salas St., Ermita, Manila', '516-1160', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (332, 'Five Star Marine Services Corporation', 'FSMSC', 'G/F NFWC Bldg., 964 J.L. Escoda corner San Marcelino Sts., Ermita,Manila', '632-5211297', 'Cynthia A. Leslie', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (333, 'Hellenic Maritime', 'HM', '1802 San Marcelino St. Cor J. Nakpil St.', '+632 385-1573', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (334, 'Gerson Skills Development Training Institute, Incorporated', 'GSDTII', '4th Flr. Guillerma Bldg. 1132 A.Mabini Street, Ermita Manila', '516-3133', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (335, 'Magsaysay MOL Marine, Inc.', 'MMMI', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (336, 'Nav Skills Training Center', 'NSTC.', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (337, 'Maritime Information Systems AS (MARIS)', 'MARIS', NULL, NULL, 'Philippe Kah', 'Technical Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (338, 'Norwegian Hull Club', 'NHC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (339, 'Mariners\' Training Institute', 'MTI Mariners', 'Rawis, Legazpi City, Phillippines', '482-0997', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (340, 'Moose and Sheep, Incorporated', 'MOST Institute', 'Khuz\'ns Bldg., M.C. Briones, North Highway Mandaue City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (341, 'Veritas  Maritime Training Center', 'VMTS', '9th Floor,Vernida IV Building, 128 L.P. Levistre St. Salcedo Villlage, Makati ', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (342, 'The Swedish Club Academy', 'TSCA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (343, 'Othello-Micomar Phils.', 'OMP', 'Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (344, 'Mariners\' Polytechnic Colleges Foundation', 'MPCF', 'Rawis, Legazpi City', '482-0997', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (345, 'Boater\'s Wheel Training Center, Inc.', 'BWTCI', '#17 Capitol Road, Lucena City', '042-660-7992', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (346, 'Monsoon Maritime Services', 'MMS', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (347, 'Don Bosco Training Center', 'Don Bosco TC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (348, 'Dohle-Philman Manning Services, Inc.', 'Dohle', 'N&M Bldg., 1184 Don Chino Roces Avenue', '899-9881', NULL, 'crewing@doehle-philman.com.ph', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (349, 'Pedrigal Welding Research and Training Center', 'PWRTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (350, 'Philsouth Maritime Training Center', 'PMTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (351, 'Norseman Company Inc.', 'NCI', 'Unit 311, 3rd Floor, S&L Building I, 1500 Roxas Boulevard, Ermita 1000 Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (352, 'Aqualink Maritime Inc.', 'AQMI', 'Rm. 605-607 Ermita Center Building, 1350 Sta. Monica St., Ermita, Manila', '0', 'Ms. Jorgina L. Arcadio -  President', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (353, 'Ace Navigation Company, Inc.', 'ACENAV', '6/F King\'s Court Building I, 2129 Chino Roces Ave., Makati City 1231', '8112251', 'Rhommel P. Pamintuan', 'Chairman/President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (354, 'Assessment and Research Center of the Philippines Inc.', 'ARC Phils', '3/F, Rm 3A Garpas Tower No. 31 V. Luna Ave cor Mabilis St., Brgy. Pinyahan, Q.C.', '+6323524775', 'Capt. Simeon B. Balita', 'General Manager', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (355, 'WSP Maritime Training Center', 'WMTC', '1802 Prestige Tower, F. Ortigas Center, Pasig City. 1605', '+6326553016', 'Manuel V. David', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (356, 'Oceanwide Maritime Services Corporation', 'CCM', '3rd Flr,G.K. Chua Building,M.J. Cuenco Ave. ,Cebu City', '032-514-6189', 'Mark Vic S. Vasquez', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (357, 'Altitude Maritime Training Center, Inc.', 'AMTCI', '951 Redo Bldg. Remedios St. cor San Marcelino St., Malate, Manila', NULL, 'Capt. Pedro U. Beriña Jr.', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (358, 'Blue Horizon Maritime Training Center, Inc.', 'BHMTCI.', 'Blue Horizon Bldg., 357 Burke St., Binondo, Manila', '243-3164 / 245-9613', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (359, 'Northwestern Mindanao Institute of Technology', 'NMIT', 'Bañadero Highway, Ozamiz City', '088-521-2189', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (360, 'World Safety Organizatin', 'WSO', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (361, 'AJ Center for Excellence, Inc.', 'ACEI', '2&5/F Delgado Bldg., Bonifacio Drive, South Harbor, Port Area, Manila', '+6323368071-74', 'Lorenzo M. Madronio', 'Training Administrative Officer', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (362, 'Navigator International Maritime Training & Assessment Ctr', 'MIMTACI', '7th Flr S&L Building 1500 Roxas Blvd.,Ermita,Manila 1000', '02 527 1069', 'Prof. Rowena M. Relano', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (363, 'Excellent Star Maritime Center Inc.', 'ESMCI', 'The travellers Life Bldg.,Rm 401 4th Flr 490 T.M. Kalaw St., corner Mabini St.', NULL, 'Ms Angelina D. Legaspi', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (364, 'Transas', 'Transas', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (365, 'United Seafarers Maritime Center,Inc.', 'USMCI', '2F Parkview Plaza,Taft Ave.,TM Kalaw St.,Ermita,Manila', '02-241-0881', 'Engr. Audie M. Macatol', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (366, 'IS Interschalt Maritime Systems', 'ISIMS', 'Osterbrooksweg 42, 22869 Schenefeld', '0', 'Capt. Roy Machart', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (367, 'BSM Crew Service Centre Philippines, Inc.', 'BSS', '1965 Leon Guinto St., Malate 1004, Manila, Philippines', '0', 'Capt. Vicente A. Dayo ', 'Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (368, 'Australian Skills Training', 'AST', '85 Mell Road, Spearwood WA 6163, Australia', '+61894343744', 'Mr. Tony Kelly', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (369, 'Le Canape', 'LCAN', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (370, 'Euro Asiatic Shipping, Inc.', 'EASI', 'Makati, Philippines', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (371, 'NE Plus Ultra Training Center Corp.', 'NEPUTCC', '707 A. Soriano Jr.,Ave,Intramuros,Manila,Philippines', NULL, 'Rose A. Arellano', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (372, 'Deckman Sea Experts Inc.', 'DSEI', '2nd Floor 801 Bldg United Nation Ave. Ermita Manila', '498-1682 / 0905-2522556', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (373, 'K Line Maritime Academy Philippines', 'KL', 'K Line Bldg., Coral Way Drive, Central Business Park 1, Pasay City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (374, 'Wagenborg Manila Inc.', 'WMI....', 'Macapagal Ave.,Pasay City', NULL, 'Paulino H. Biscocho Jr.', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (375, 'Niederelbe Schiffahrt Gesellschaft mbh Co. KG', 'NSGCK', 'Hamburger Street 4, 21614 Buxtehude, Germany', 'none', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (376, 'Tat Hong Training Center', 'THTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (377, 'Sealand Skills Development Center Inc.', 'SSDCI', '5th Floor Jemarsons Place, 1626 P. Hidalgo Lim St., Malate, Manila', '7157', 'Ms. Marielle M. Tibayan', 'Administration Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (378, 'Furuno Electric Co., Ltd.', 'FEC', '9-52 Ashihara-cho, Nishinomiya, 662-8580 Japan', '+81 798 63-1072', 'Muneyuki Koike', 'Senior Managing Director', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (379, 'The International Association of Independent Tanker Owners', 'INTANKO', 'Nedre Vollgate, 4  Oslo 0106 Norway', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (380, 'SEAMATE', 'SEAMAT', '1026 Belen St., corner Gen Luna St.,Paco ,Metro Manila', NULL, 'Capt. Paul James C. Llamas', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (381, 'Ship Engrs & Mates Assessment,Trng&Education & Maritime Svcs', 'SEMATEMS', '1026 Belen St. cor Gen.Luna St.,Paco, Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (382, 'International Maritime Education Center Corporation', 'IMECC', '8-12th Floors Maritime Plaza Bldg, A.Flores corner Cortada Sts. Ermita Manila', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (383, 'NAUTICA', 'NAUTICA', '7th Flr De Leon Building,M.H. Del Pilar Cor Nuestra Señora De Guia,Ermita,Manila', NULL, 'Capt. Richard G. Gamayao', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (384, 'FURUNO NORGE', 'FNORGE', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (385, 'Noble Maritime and Offshore Training Center Services Corp.', 'NMOTCSC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (386, 'Dessert Draft', 'DD', 'Project 2, Quezon City', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (387, 'SEAMAC International Training Institute', 'SITI', 'G/F 867 G. Tolentino St. Sampaloc, Manila', '02 7367885', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (388, 'Norteam Shipping Services Inc.', 'NSSI', 'Suite 201 ITC Bldg., 337 Sen. Gil Puyat Ave, Makati City', '02 8907746', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (389, 'International Tourism and Culinary Development School', 'ITCDS', '1021 Apacible St., Paco, Manila', '02 5232542', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (390, 'United International Maritime Training and Assessment Center', 'UIMT', '4th Flr. Seatower Bldg. 2332 Roxas Blvd., Pasay City', '028230918', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (391, 'STC B.V.', 'STCBV', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (392, 'FURUNO INS Training Center (INSTC)', 'FINSTC', 'No. 17 Loyang Lane, Singapore 508917', '+65 67458472', 'Mr. Ong Kin Song', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (393, 'KGJ Cement', 'KGJ', NULL, NULL, NULL, 'Netherlands', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (394, 'Mariana Academy of Maritime Studies Inc.', 'MAMS', 'GE Antonio Bldg, TM Kalaw, Ermita, Manila', '+632 5262395', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (395, 'Thenamaris Philippines Inc.', 'THENA', '/F Marbella Manila II Building, 2071 Roxas Boulevard, Barangay 701, Malate, Mani', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (396, 'Shipgaz Training AB', 'SGTAB', 'Kungsgatan 4, SE-411 19 Gothenburg', '+46 31–712 17 70', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (397, 'Man Primeserve Academy - Holeby', 'MANPA', 'MAN Diesel & Turbo H. Christoffersensvej 6 4960  Holeby Denmark', '+45 5469 3100', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (398, 'Primeserve Academy - Copenhagen', 'MPAC', 'MAN Diesel & Turbo SE Teglholmsgade 35 DK-2450  Copenhagen SV Denmark', '+45 33 85 22 27', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (399, 'United Marine Training Center', 'UMTCM', '2120 Leon Guinto Street Malate, 1004 Malate, Manila, Philippines', '+63 2 981 6682', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (400, 'DNV.GL', 'DNVGL', 'DNV GL SE Marinte Headquarters Hamburg, Germany', '+49-40-36149-0', 'Mariela Verhaaf-Olieberg', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (401, 'BIM Maritime Training Center', 'BIMMTC', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (402, 'ZRC Training  and Assessment Center Phils., Inc.', 'ZRC.', '2/F Rm. 204 Ermita Center Bldg.,Roxas Blvd. cor Sta. Monica St.,Ermita Manila,Ph', '354-6869', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (403, 'MTC Maritime Training Center', 'MTC.', 'Schnackenburgallee 149 l 22525 Hamburg Germany', '+49 533 07 42-0', NULL, 'Fax. +49 533 07 42-69', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (404, 'Pentagon Nautical Technological Center, Inc.', 'PNTCI', '2nd Floor Citadel/Delgado Bldg., 637 Bonifacio Drive cor 25th St., Port Area', '+6322543873', 'Ms. Enriqueta B. Mendez', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (405, 'Atlantic Grains Inc.', 'AGI', 'Sitio Acasia.Malainen,Bago,Naic,Cavite', NULL, 'John Y. Poon', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (406, 'Safe Site', 'SS', NULL, '+31 78 69 33 499', 'Nick de Zeeuw', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (407, 'GigaMare Inc.', 'GMI', 'Bldg. 2082/2083 Corregidor Highway Naval Magazine Area Subic Bay Freeport Zone', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (408, 'Zamboanga Maritime Training Center', 'ZMTC', '60 Campaner St., Zamboanga ', '062 992-7358', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (409, 'Hammer Maritime, Inc.', 'HMI', 'Section D-5th Floor Ramon Magsaysay Center 1680 Roxas Blvd.', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (410, 'Multinational Maritime, Inc.', 'MMI', '3/F Room 301, MMS Bacoor Bldg. ', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (411, 'Federal Republic of Germany', 'FRG', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (412, 'FEATI Maritime Training & Assessment Center', 'FMTAC', '2nd Floor, Building 1, FEATI University Compound, Helios St., Sta. Cruz, Manila,', NULL, 'Capt. Edgar Allan T. Acosta', 'Board of Marine Deck Officer', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (413, 'Shipgaz Training', 'SGT', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (414, 'Arion Satellite Services', 'ARIONQ', 'Pusan, Korea', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (415, 'Norwegian Maritime Authority', 'NMA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (416, 'Lanka Academy of Technological Studies', 'LATS', 'Fishery Harbour, Modara, Moratuwa, Sri Lanka', '0094-038-4281556', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (417, 'Power Link', 'PowLink', '2/F Marbella II Bldg., 2071 Roxas Blvd., Malate, Manila', 'N/A', 'Mr. Francis Tajanlangit', 'President', 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (418, 'SIMRAD (Safebridge GmbH)', 'Safebridge..', 'Breite Strate 61, 22767 Hamburg, Germany', '+49 (40) 55565791-15', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (419, 'Dienst Scheepvaartcontrole', 'DSA', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (420, 'University of Perpetual Help System-Maritime Training Center', 'UPHS', 'Brgy. Marinig, Cabuyao, Laguna', NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (421, 'RCTI Training & Assessment Corp.', 'RCTI', 'Roxas Blvd. Ermita, Manila', '+632 5237652', NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (422, 'GASS Teknikk', 'GT', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (423, 'CLAS Training And Assessment Corp.', 'CLAS', '4th Floor, GMT II Building, Junquera corner P. del Royal St., Cebu City', NULL, 'Capt. Anthony C. Aranas', NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (424, 'West Visayas State University', 'WVSU', NULL, NULL, NULL, NULL, 2, NULL, NULL);
INSERT INTO `training_centers` VALUES (425, 'Navigation Center for Advanced Simulators and Trainings,Inc.', 'NCASTI', '2nd Floor EMI Bldg #1181 Leveriza St. Cor. Pres.Quirino Ave. Malate, Manila', NULL, NULL, NULL, 2, NULL, NULL);
